/*
  list of the partecipants of the ops from discord (for now)
  API for PS2 and discord from .env

  https://discordjs.guide/preparations/setting-up-a-bot-application.html#creating-your-bot

  https://discord.com/developers/applications/794697883596881940/information

  http://census.daybreakgames.com/get/ps2:v2/characters_event/?character_id=5428016459730317697,5428117870052769409&c:limit=100&type=KILL,DEATH
  http://census.daybreakgames.com/s:example/json/get/ps2:v2/character/5428016459730317697
  http://census.daybreakgames.com/get/ps2:v2/character/?name.first_lower=pholanx


  My obj(dict) will be
  players = {
    <id>:{"name":<name>, "heals":<heals>, etc }
  }
*/
const dotenv = require('dotenv');
const WebSocket = require('ws');
const got = require('got');

require('dotenv').config();

// I get my ID from the names (taken from discord)
// TODO: clean the names from @ or [BJAY]
// TODO: get lowercase
// const list_of_names = ["fofila", "vaaragh"]
const list_of_names = ["fofila"]
const dict_of_values = {}


main();


/*
  given the name of the player, the info(params) needed and the dictionary you want to populate
  call the PS2 API and add the response to the dict
*/
async function setIDfromName(name=null, params="&c:show=character_id", dict=dict_of_values){
  // TODO: if name is empty crash
  try {
    var response = await got(`http://census.daybreakgames.com/get/ps2:v2/character/?name.first_lower=${name}${params}`);
    console.log(JSON.parse(response.body).character_list[0].character_id)
    dict_of_values[JSON.parse(response.body).character_list[0].character_id] = {}
    dict_of_values[JSON.parse(response.body).character_list[0].character_id]["name"] = name;
    console.log(dict_of_values);
  } catch (error) {
    console.log(error);
  }
}

/*
  function that creates the connection to the WS
*/
async function createWSConnection(url_to_ws){
  const connection = new WebSocket(url_to_ws)
  /*
    navigate di e.data to get the value needed
    TODO: add a list as a log of events
  */
  connection.onmessage = (e) => {
    console.log(e.data)
  }
  connection.onerror = error => {console.error(`WebSocket error: ${error}`)}
  return connection;
}

/*
  from a list of names get the ID and populate
*/
async function populate_names(names){
  for (let i = 0; i < names.length; i++) {
    setIDfromName(names[i]);  
  }
}

/*
  the first function (needed for the async hell)
*/
async function main(){
  await populate_names(list_of_names);
  console.log(dict_of_values);
  const ws = await createWSConnection(`wss://push.planetside2.com/streaming?environment=ps2&service-id=s:${process.env.PS2_TOKEN}`);
  ws.onopen = () => {
    list_of_ids = []
    for (const id in dict_of_values) {
      list_of_ids.push(id)
    }
    console.info('Connection to PS2 server open!')
    ws.send('{"action":"clearSubscribe","all":"true","service":"event"}')
    let message = `{"service":"event","action":"subscribe","characters":[${list_of_ids}],"eventNames":["GainExperience_experience_id_4","GainExperience_experience_id_5","GainExperience_experience_id_7"]}`;
    console.log(message);
    // TODO: unsubscribe to heartbeat
    ws.send(message)
    // ws.send('{"service":"event","action":"help"}')
  } 
}



// for future use
const type_gain_experience = {
  "Kill Player": "GainExperienc_experience_id_1",
  "Kill Player Assist": "GainExperienc_experience_id_2",
  "Kill Player Spawn Assist": "GainExperienc_experience_id_3",
  "Heal Player": "GainExperienc_experience_id_4",
  "Heal Assist": "GainExperienc_experience_id_5",
  "MAX Repair": "GainExperienc_experience_id_6",
  "Revive": "GainExperienc_experience_id_7",
  "Kill Streak": "GainExperienc_experience_id_8",
  "Domination Kill": "GainExperienc_experience_id_10",
  "Revenge Kill": "GainExperienc_experience_id_11",
  "Control Point - Defend": "GainExperienc_experience_id_15",
  "Control Point - Attack": "GainExperienc_experience_id_16",
  "Facility Captured (Not Used)": "GainExperienc_experience_id_19",
  "Destroy Secondary Objective": "GainExperienc_experience_id_21",
  "Destroy SecondaryObjectiveAssist": "GainExperienc_experience_id_22",
  "Vehicle Destruction - Flash": "GainExperienc_experience_id_24",
  "Multiple Kill": "GainExperienc_experience_id_25",
  "Vehicle RoadKill": "GainExperienc_experience_id_26",
  "Squad Repair - Flash": "GainExperienc_experience_id_28",
  "Kill Player Class MAX": "GainExperienc_experience_id_29",
  "Transport Assist": "GainExperienc_experience_id_30",
  "Vehicle Repair - Flash": "GainExperienc_experience_id_31",
  "Nemesis Kill": "GainExperienc_experience_id_32",
  "Resupply Player": "GainExperienc_experience_id_34",
  "Spot Kill": "GainExperienc_experience_id_36",
  "Headshot": "GainExperienc_experience_id_37",
  "Stop Kill Streak": "GainExperienc_experience_id_38",
  "Meta Game Event reward": "GainExperienc_experience_id_47",
  "Squad Heal": "GainExperienc_experience_id_51",
  "Squad Revive": "GainExperienc_experience_id_53",
  "Squad Spot Kill": "GainExperienc_experience_id_54",
  "Squad Resupply": "GainExperienc_experience_id_55",
  "Squad Spawn": "GainExperienc_experience_id_56",
  "Destroy Engineer Turret": "GainExperienc_experience_id_57",
  "Vehicle Destruction - Phalanx": "GainExperienc_experience_id_58",
  "Vehicle Destruction - Drop Pod": "GainExperienc_experience_id_59",
  "Vehicle Destruction - Galaxy": "GainExperienc_experience_id_60",
  "Vehicle Destruction - Liberator": "GainExperienc_experience_id_61",
  "Vehicle Destruction - Lightning": "GainExperienc_experience_id_62",
  "Vehicle Destruction - Magrider": "GainExperienc_experience_id_63",
  "Vehicle Destruction - Mosquito": "GainExperienc_experience_id_64",
  "Vehicle Destruction - Prowler": "GainExperienc_experience_id_65",
  "Vehicle Destruction - Reaver": "GainExperienc_experience_id_66",
  "Vehicle Destruction - Scythe": "GainExperienc_experience_id_67",
  "Vehicle Destruction - Sunderer": "GainExperienc_experience_id_68",
  "Vehicle Destruction - Vanguard": "GainExperienc_experience_id_69",
  "Vehicle Ram Bonus": "GainExperienc_experience_id_72",
  "Vehicle Ram Kill - Engi Turret": "GainExperienc_experience_id_73",
  "Vehicle Ram Kill - Phalanx": "GainExperienc_experience_id_74",
  "Vehicle Ram Kill - Drop Pod": "GainExperienc_experience_id_75",
  "Vehicle Ram Kill - Galaxy": "GainExperienc_experience_id_76",
  "Vehicle Ram Kill - Liberator": "GainExperienc_experience_id_77",
  "Vehicle Ram Kill - Lightning": "GainExperienc_experience_id_78",
  "Vehicle Ram Kill - Magrider": "GainExperienc_experience_id_79",
  "Vehicle Ram Kill - Mosquito": "GainExperienc_experience_id_80",
  "Vehicle Ram Kill - Prowler": "GainExperienc_experience_id_81",
  "Vehicle Ram Kill - Reaver": "GainExperienc_experience_id_82",
  "Vehicle Ram Kill - Scythe": "GainExperienc_experience_id_83",
  "Vehicle Ram Kill - Sunderer": "GainExperienc_experience_id_84",
  "Vehicle Ram Kill - Vanguard": "GainExperienc_experience_id_85",
  "Explosive Destruction": "GainExperienc_experience_id_86",
  "Secondary Facility Object Repair": "GainExperienc_experience_id_87",
  "Vehicle Repair - Engi Turret": "GainExperienc_experience_id_88",
  "Vehicle Repair - Phalanx": "GainExperienc_experience_id_89",
  "Vehicle Repair - Drop Pod": "GainExperienc_experience_id_90",
  "Vehicle Repair - Galaxy": "GainExperienc_experience_id_91",
  "Vehicle Repair - Liberator": "GainExperienc_experience_id_92",
  "Vehicle Repair - Lightning": "GainExperienc_experience_id_93",
  "Vehicle Repair - Magrider": "GainExperienc_experience_id_94",
  "Vehicle Repair - Mosquito": "GainExperienc_experience_id_95",
  "Vehicle Repair - Prowler": "GainExperienc_experience_id_96",
  "Vehicle Repair - Reaver": "GainExperienc_experience_id_97",
  "Vehicle Repair - Scythe": "GainExperienc_experience_id_98",
  "Vehicle Repair - Sunderer": "GainExperienc_experience_id_99",
  "Vehicle Repair - Vanguard": "GainExperienc_experience_id_100",
  "Kill Assist - Flash": "GainExperienc_experience_id_101",
  "Kill Assist - Engi Turret": "GainExperienc_experience_id_102",
  "Kill Assist - Phalanx": "GainExperienc_experience_id_103",
  "Kill Assist - Drop Pod": "GainExperienc_experience_id_104",
  "Kill Assist - Galaxy": "GainExperienc_experience_id_105",
  "Kill Assist - Liberator": "GainExperienc_experience_id_106",
  "Kill Assist - Lightning": "GainExperienc_experience_id_107",
  "Kill Assist - Magrider": "GainExperienc_experience_id_108",
  "Kill Assist - Mosquito": "GainExperienc_experience_id_109",
  "Kill Assist - Prowler": "GainExperienc_experience_id_110",
  "Kill Assist - Reaver": "GainExperienc_experience_id_111",
  "Kill Assist - Scythe": "GainExperienc_experience_id_112",
  "Kill Assist - Sunderer": "GainExperienc_experience_id_113",
  "Kill Assist - Vanguard": "GainExperienc_experience_id_114",
  "Squad Repair - Engi Turret": "GainExperienc_experience_id_129",
  "Squad Repair - Phalanx": "GainExperienc_experience_id_130",
  "Squad Repair - Drop Pod": "GainExperienc_experience_id_131",
  "Squad Repair - Galaxy": "GainExperienc_experience_id_132",
  "Squad Repair - Liberator": "GainExperienc_experience_id_133",
  "Squad Repair - Lightning": "GainExperienc_experience_id_134",
  "Squad Repair - Magrider": "GainExperienc_experience_id_135",
  "Squad Repair - Mosquito": "GainExperienc_experience_id_136",
  "Squad Repair - Prowler": "GainExperienc_experience_id_137",
  "Squad Repair - Reaver": "GainExperienc_experience_id_138",
  "Squad Repair - Scythe": "GainExperienc_experience_id_139",
  "Squad Repair - Sunderer": "GainExperienc_experience_id_140",
  "Squad Repair - Vanguard": "GainExperienc_experience_id_141",
  "Squad MAX Repair": "GainExperienc_experience_id_142",
  "Drop Pod Kill": "GainExperienc_experience_id_143",
  "Player Kill by Sunderer Gunner": "GainExperienc_experience_id_146",
  "Player Kill by Magrider Gunner": "GainExperienc_experience_id_148",
  "Player Kill by Vanguard Gunner": "GainExperienc_experience_id_149",
  "Player Kill by Prowler Gunner": "GainExperienc_experience_id_150",
  "Player Kill by Liberator Gunner": "GainExperienc_experience_id_154",
  "Player Kill by Galaxy Gunner": "GainExperienc_experience_id_155",
  "Flash Kill by Sunderer Gunner": "GainExperienc_experience_id_159",
  "Sunderer Kill by Sunderer Gunner": "GainExperienc_experience_id_160",
  "Lightning Kill by Sunderer Gunne": "GainExperienc_experience_id_161",
  "Magrider Kill by Sunderer Gunner": "GainExperienc_experience_id_162",
  "Vanguard Kill by Sunderer Gunner": "GainExperienc_experience_id_163",
  "Prowler Kill by Sunderer Gunner": "GainExperienc_experience_id_164",
  "Scythe Kill by Sunderer Gunner": "GainExperienc_experience_id_165",
  "Reaver Kill by Sunderer Gunner": "GainExperienc_experience_id_166",
  "Mosquito Kill by Sunderer Gunner": "GainExperienc_experience_id_167",
  "Lib Kill by Sunderer": "GainExperienc_experience_id_168",
  "Galaxy Kill by Sunderer Gunner": "GainExperienc_experience_id_169",
  "Flash Kill by Magrider Gunner": "GainExperienc_experience_id_181",
  "Sunderer Kill by Magrider Gunner": "GainExperienc_experience_id_182",
  "Lightning Kill by Magrider Gunne": "GainExperienc_experience_id_183",
  "Vanguard Kill by Magrider Gunner": "GainExperienc_experience_id_184",
  "Prowler Kill by Magrider Gunner": "GainExperienc_experience_id_185",
  "Reaver Kill by Magrider Gunner": "GainExperienc_experience_id_186",
  "Mosquito Kill by Magrider Gunner": "GainExperienc_experience_id_187",
  "Lib Kill by Magrider": "GainExperienc_experience_id_188",
  "Galaxy Kill by Magrider Gunner": "GainExperienc_experience_id_189",
  "Flash Kill by Vanguard Gunner": "GainExperienc_experience_id_190",
  "Sunderer Kill by Vanguard Gunner": "GainExperienc_experience_id_191",
  "Lightning Kill by Vanguard Gunne": "GainExperienc_experience_id_192",
  "Magrider Kill by Vanguard Gunner": "GainExperienc_experience_id_193",
  "Prowler Kill by Vanguard Gunner": "GainExperienc_experience_id_195",
  "Scythe Kill by Vanguard Gunner": "GainExperienc_experience_id_196",
  "Mosquito Kill by Vanguard Gunner": "GainExperienc_experience_id_197",
  "Lib Kill by Vanguard": "GainExperienc_experience_id_198",
  "Galaxy Kill by Vanguard Gunner": "GainExperienc_experience_id_199",
  "Flash Kill by Prowler Gunner": "GainExperienc_experience_id_200",
  "Galaxy Spawn Bonus": "GainExperienc_experience_id_201",
  "Sunderer Kill by Prowler Gunner": "GainExperienc_experience_id_202",
  "Lightning Kill by Prowler Gunner": "GainExperienc_experience_id_203",
  "Magrider Kill by Prowler Gunner": "GainExperienc_experience_id_204",
  "Vanguard Kill by Prowler Gunner": "GainExperienc_experience_id_205",
  "Scythe Kill by Prowler Gunner": "GainExperienc_experience_id_207",
  "Reaver Kill by Prowler Gunner": "GainExperienc_experience_id_208",
  "Liberator Kill by Prowler Gunner": "GainExperienc_experience_id_209",
  "Galaxy Kill by Prowler Gunner": "GainExperienc_experience_id_210",
  "Flash Kill by Liberator Gunner": "GainExperienc_experience_id_211",
  "Sunderer Kill by Lib Gunner": "GainExperienc_experience_id_212",
  "Lightning Kill by Liberator Gunn": "GainExperienc_experience_id_213",
  "Magrider Kill by Lib Gunner": "GainExperienc_experience_id_214",
  "Vanguard Kill by Lib Gunner": "GainExperienc_experience_id_215",
  "Prowler Kill by Liberator Gunner": "GainExperienc_experience_id_216",
  "Scythe Kill by Liberator Gunner": "GainExperienc_experience_id_217",
  "Reaver Kill by Liberator Gunner": "GainExperienc_experience_id_218",
  "Mosquito Kill by Lib Gunner": "GainExperienc_experience_id_219",
  "Lib Kill by Liberator": "GainExperienc_experience_id_220",
  "Galaxy Kill by Liberator Gunner": "GainExperienc_experience_id_221",
  "Flash Kill by Galaxy Gunner": "GainExperienc_experience_id_222",
  "Sunderer Kill by Galaxy Gunner": "GainExperienc_experience_id_223",
  "Lightning Kill by Galaxy Gunner": "GainExperienc_experience_id_224",
  "Magrider Kill by Galaxy Gunner": "GainExperienc_experience_id_225",
  "Vanguard Kill by Galaxy Gunner": "GainExperienc_experience_id_226",
  "Prowler Kill by Galaxy Gunner": "GainExperienc_experience_id_227",
  "Scythe Kill by Galaxy Gunner": "GainExperienc_experience_id_228",
  "Reaver Kill by Galaxy Gunner": "GainExperienc_experience_id_229",
  "Mosquito Kill by Galaxy Gunner": "GainExperienc_experience_id_230",
  "LibKill by Galaxy Gunner": "GainExperienc_experience_id_231",
  "Galaxy Kill by Galaxy Gunner": "GainExperienc_experience_id_232",
  "Sunderer Spawn Bonus": "GainExperienc_experience_id_233",
  "Facility placed bomb": "GainExperienc_experience_id_234",
  "Facility defused bomb": "GainExperienc_experience_id_235",
  "Facility Terminal Hack": "GainExperienc_experience_id_236",
  "Facility Turret Hack": "GainExperienc_experience_id_237",
  "Vehicle Resupply": "GainExperienc_experience_id_240",
  "Squad Vehicle Resupply": "GainExperienc_experience_id_241",
  "Spot Kill - Flash": "GainExperienc_experience_id_242",
  "Spot Kill - Engi Turret": "GainExperienc_experience_id_243",
  "Spot Kill - Phalanx": "GainExperienc_experience_id_244",
  "Spot Kill - Drop Pod": "GainExperienc_experience_id_245",
  "Spot Kill - Galaxy": "GainExperienc_experience_id_246",
  "Spot Kill - Liberator": "GainExperienc_experience_id_247",
  "Spot Kill - Lightning": "GainExperienc_experience_id_248",
  "Spot Kill - Magrider": "GainExperienc_experience_id_249",
  "Spot Kill - Mosquito": "GainExperienc_experience_id_250",
  "Spot Kill - Prowler": "GainExperienc_experience_id_251",
  "Spot Kill - Reaver": "GainExperienc_experience_id_252",
  "Spot Kill - Scythe": "GainExperienc_experience_id_253",
  "Spot Kill - Sunderer": "GainExperienc_experience_id_254",
  "Spot Kill - Vanguard": "GainExperienc_experience_id_255",
  "Squad Spot Kill - Flash": "GainExperienc_experience_id_256",
  "Squad Spot Kill - Engi Turret": "GainExperienc_experience_id_257",
  "Squad Spot Kill - Phalanx": "GainExperienc_experience_id_258",
  "Squad Spot Kill - Drop Pod": "GainExperienc_experience_id_259",
  "Squad Spot Kill - Galaxy": "GainExperienc_experience_id_260",
  "Squad Spot Kill - Liberator": "GainExperienc_experience_id_261",
  "Squad Spot Kill - Lightning": "GainExperienc_experience_id_262",
  "Squad Spot Kill - Magrider": "GainExperienc_experience_id_263",
  "Squad Spot Kill - Mosquito": "GainExperienc_experience_id_264",
  "Squad Spot Kill - Prowler": "GainExperienc_experience_id_265",
  "Squad Spot Kill - Reaver": "GainExperienc_experience_id_266",
  "Squad Spot Kill - Scythe": "GainExperienc_experience_id_267",
  "Squad Spot Kill - Sunderer": "GainExperienc_experience_id_268",
  "Squad Spot Kill - Vanguard": "GainExperienc_experience_id_269",
  "Squad Spawn Beacon Kill": "GainExperienc_experience_id_270",
  "Convert Capture Point": "GainExperienc_experience_id_272",
  "Terminal Kill": "GainExperienc_experience_id_275",
  "Terminal Repair": "GainExperienc_experience_id_276",
  "Spawn Kill": "GainExperienc_experience_id_277",
  "Priority Kill": "GainExperienc_experience_id_278",
  "High Priority Kill": "GainExperienc_experience_id_279",
  "Lighting Damage (Infantry vs Vehicle)": "GainExperienc_experience_id_280",
  "Prowler Damage (Infantry vs Vehicle)": "GainExperienc_experience_id_281",
  "Galaxy Damage": "GainExperienc_experience_id_283",
  "Liberator Damage": "GainExperienc_experience_id_284",
  "Magrider Damage (Infantry vs Vehicle)": "GainExperienc_experience_id_285",
  "Mosquito Damage": "GainExperienc_experience_id_286",
  "Reaver Damage": "GainExperienc_experience_id_287",
  "Scythe Damage": "GainExperienc_experience_id_288",
  "Sunderer Damage (Infantry vs Vehicle)": "GainExperienc_experience_id_289",
  "Vanguard Damage (Infantry vs Vehicle)": "GainExperienc_experience_id_290",
  "Ribbon Experience": "GainExperienc_experience_id_291",
  "Motion Detect": "GainExperienc_experience_id_293",
  "Squad Motion Spot": "GainExperienc_experience_id_294",
  "Vehicle Ram Kill - Harasser": "GainExperienc_experience_id_300",
  "Vehicle Destruction - Harasser": "GainExperienc_experience_id_301",
  "Squad Repair - Harasser": "GainExperienc_experience_id_302",
  "Vehicle Repair - Harasser": "GainExperienc_experience_id_303",
  "Kill Assist - Harasser": "GainExperienc_experience_id_304",
  "Spot Kill - Harasser": "GainExperienc_experience_id_306",
  "Squad Spot Kill - Harasser": "GainExperienc_experience_id_307",
  "Harasser Kill by Sunderer Gunne": "GainExperienc_experience_id_308",
  "Harasser Kill by Magrider Gunne": "GainExperienc_experience_id_309",
  "Harasser Kill by Vanguard Gunne": "GainExperienc_experience_id_310",
  "Harasser Kill by Prowler Gunner": "GainExperienc_experience_id_311",
  "Harasser Kill by Liberator Gunn": "GainExperienc_experience_id_312",
  "Harasser Kill by Galaxy Gunner": "GainExperienc_experience_id_313",
  "Player Kill by Harasser Gunner": "GainExperienc_experience_id_314",
  "Flash Kill by Harasser Gunner": "GainExperienc_experience_id_315",
  "Sunderer Kill by Harasser Gunner": "GainExperienc_experience_id_316",
  "Lightning Kill by Harasser Gunne": "GainExperienc_experience_id_317",
  "Vanguard Kill by Harasser Gunner": "GainExperienc_experience_id_318",
  "Prowler Kill by Harasser Gunner": "GainExperienc_experience_id_319",
  "Reaver Kill by Harasser Gunner": "GainExperienc_experience_id_320",
  "Mosquito Kill by Harasser Gunner": "GainExperienc_experience_id_321",
  "Lib Kill by Harasser": "GainExperienc_experience_id_322",
  "Galaxy Kill by Harasser Gunner": "GainExperienc_experience_id_323",
  "Harasser Kill by Harasser Gunner": "GainExperienc_experience_id_324",
  "Magrider Kill by Harasser Gunner": "GainExperienc_experience_id_325",
  "Scythe Kill by Harasser Gunner": "GainExperienc_experience_id_326",
  "Tank Mine Despawn/Defusal": "GainExperienc_experience_id_327",
  "Alert Reward": "GainExperienc_experience_id_328",
  "Tank Hunter Bonus - Prowler Kill": "GainExperienc_experience_id_322",
  "Tank Hunter Bonus - Magrider Kil": "GainExperienc_experience_id_330",
  "Dogfighter Bonus - Mosquito Kill": "GainExperienc_experience_id_331",
  "Dogfighter Bonus - Reaver Kill": "GainExperienc_experience_id_332",
  "Dogfighter Bonus - Scythe Kill": "GainExperienc_experience_id_333",
  "Tank Hunter Bonus - Vanguard Kil": "GainExperienc_experience_id_334",
  "Savior Kill (Non MAX)": "GainExperienc_experience_id_335",
  "Saved": "GainExperienc_experience_id_336",
  "Holiday Event NPC: Kill": "GainExperienc_experience_id_337",
  "Holiday Event NPC Gold: Kill": "GainExperienc_experience_id_338",
  "Snowman Kill by Sunderer Gunner": "GainExperienc_experience_id_339",
  "Snowman Kill by Magrider Gunner": "GainExperienc_experience_id_340",
  "Snowman Kill by Vanguard Gunner": "GainExperienc_experience_id_341",
  "Snowman Kill by Prowler Gunner": "GainExperienc_experience_id_342",
  "Snowman Kill by Liberator Gunner": "GainExperienc_experience_id_343",
  "Snowman Kill by Galaxy Gunner": "GainExperienc_experience_id_344",
  "Snowman Kill by Harasser Gunner": "GainExperienc_experience_id_345",
  "GSnowman Kill by Sunder Gunner": "GainExperienc_experience_id_346",
  "GSnowman Kill by Mag Gunner": "GainExperienc_experience_id_347",
  "GSnowman Kill by Vang Gunner": "GainExperienc_experience_id_348",
  "GSnowman Kill by Prow Gunner": "GainExperienc_experience_id_349",
  "GSnowman Kill by Lib Gunner": "GainExperienc_experience_id_350",
  "GSnowman Kill by Gal Gunner": "GainExperienc_experience_id_351",
  "GSnowman Kill by Haras Gunner": "GainExperienc_experience_id_352",
  "Scout Radar Detect": "GainExperienc_experience_id_353",
  "Squad Scout Radar Detect": "GainExperienc_experience_id_354",
  "Squad Vehicle Spawn Bonus": "GainExperienc_experience_id_355",
  "Vehicle Ram Kill - R Drone": "GainExperienc_experience_id_356",
  "Vehicle Destruction - R Drone": "GainExperienc_experience_id_357",
  "Squad Repair - R Drone": "GainExperienc_experience_id_358",
  "Vehicle Repair - R Drone": "GainExperienc_experience_id_359",
  "Kill Assist - R Drone": "GainExperienc_experience_id_360",
  "R Drone Kill by Harasser Gunner": "GainExperienc_experience_id_362",
  "R Drone Kill by Sunderer Gunner": "GainExperienc_experience_id_363",
  "R Drone Kill by Magrider Gunner": "GainExperienc_experience_id_364",
  "R Drone Kill by Prowler Gunner": "GainExperienc_experience_id_365",
  "R Drone Kill by Lib Gunner": "GainExperienc_experience_id_366",
  "R Drone Kill by Galaxy Gunner": "GainExperienc_experience_id_367",
  "Spot Kill - R Drone": "GainExperienc_experience_id_368",
  "Squad Spot Kill - R Drone": "GainExperienc_experience_id_369",
  "Motion Sensor Spotter Kill": "GainExperienc_experience_id_370",
  "Kill Player Priority Assist": "GainExperienc_experience_id_371",
  "Kill Player High Priority Assist": "GainExperienc_experience_id_372",
  "Shield Regen Tool Kill": "GainExperienc_experience_id_437",
  "Shield Repair": "GainExperienc_experience_id_438",
  "Squad Shield Repair": "GainExperienc_experience_id_439",
  "Chain Expl Assist: Infantry": "GainExperienc_experience_id_440",
  "Chain Expl Assist: Flash": "GainExperienc_experience_id_441",
  "Vehicle Destruction - Valkyrie": "GainExperienc_experience_id_501",
  "Vehicle Ram Kill - Valkyrie": "GainExperienc_experience_id_502",
  "Vehicle Repair - Valkyrie": "GainExperienc_experience_id_503",
  "Kill Assist - Valkyrie": "GainExperienc_experience_id_504",
  "Squad Repair - Valkyrie": "GainExperienc_experience_id_505",
  "Spot Kill - Valkyrie": "GainExperienc_experience_id_506",
  "Squad Spot Kill - Valkyrie": "GainExperienc_experience_id_507",
  "Valkyrie Damage": "GainExperienc_experience_id_508",
  "Valkyrie Kill by Sunderer Gunner": "GainExperienc_experience_id_509",
  "Valkyrie Kill by Magrider Gunner": "GainExperienc_experience_id_510",
  "Valkyrie Kill by Vanguard Gunner": "GainExperienc_experience_id_511",
  "Valkyrie Kill by Prowler Gunner": "GainExperienc_experience_id_512",
  "Valkyrie Kill by Liberator Gunner": "GainExperienc_experience_id_513",
  "Valkyrie Kill by Galaxy Gunner": "GainExperienc_experience_id_514",
  "Player Kill by Valkyrie Gunner": "GainExperienc_experience_id_515",
  "Flash Kill by Valkyrie Gunner": "GainExperienc_experience_id_520",
  "Sunderer Kill by Valkyrie Gunner": "GainExperienc_experience_id_521",
  "Lightning Kill by Valkyrie Gunne": "GainExperienc_experience_id_522",
  "Vanguard Kill by Valkyrie Gunner": "GainExperienc_experience_id_523",
  "Prowler Kill by Valkyrie Gunner": "GainExperienc_experience_id_524",
  "Reaver Kill by Valkyrie Gunner": "GainExperienc_experience_id_525",
  "Mosquito Kill by Valkyrie Gunner": "GainExperienc_experience_id_526",
  "Lib Kill by Valkyrie": "GainExperienc_experience_id_527",
  "Galaxy Kill by Valkyrie Gunner": "GainExperienc_experience_id_528",
  "Magrider Kill by Valkyrie Gunner": "GainExperienc_experience_id_529",
  "Scythe Kill by Valkyrie Gunner": "GainExperienc_experience_id_530",
  "Snowman Kill by Valkyrie Gunner": "GainExperienc_experience_id_531",
  "R Drone Kill by Valkyrie Gunner": "GainExperienc_experience_id_532",
  "Valkyrie Kill by Valkyrie Gunner": "GainExperienc_experience_id_533",
  "Chain Expl Assist: Phalanx": "GainExperienc_experience_id_534",
  "Chain Expl Assist: Drop Pod": "GainExperienc_experience_id_535",
  "Chain Expl Assist: Galaxy": "GainExperienc_experience_id_536",
  "Chain Expl Assist: Liberator": "GainExperienc_experience_id_537",
  "Chain Expl Assist: Lightning": "GainExperienc_experience_id_538",
  "Chain Expl Assist: Magrider": "GainExperienc_experience_id_539",
  "Chain Expl Assist: Mosquito": "GainExperienc_experience_id_540",
  "Chain Expl Assist: Prowler": "GainExperienc_experience_id_541",
  "Chain Expl Assist: Reaver": "GainExperienc_experience_id_542",
  "Chain Expl Assist: Scythe": "GainExperienc_experience_id_543",
  "Chain Expl Assist: Sunderer": "GainExperienc_experience_id_544",
  "Chain Expl Assist: Vanguard": "GainExperienc_experience_id_545",
  "Chain Expl Assist: Harasser": "GainExperienc_experience_id_546",
  "Chain Expl Assist: R Drone": "GainExperienc_experience_id_547",
  "Chain Expl Assist: Valkyrie": "GainExperienc_experience_id_548",
  "Concussion Grenade Assist": "GainExperienc_experience_id_550",
  "Concussion Grenade Squad Assist": "GainExperienc_experience_id_551",
  "EMP Grenade Assist": "GainExperienc_experience_id_552",
  "EMP Grenade Squad Assist": "GainExperienc_experience_id_553",
  "Flashbang Assist": "GainExperienc_experience_id_554",
  "Flashbang Squad Assist": "GainExperienc_experience_id_555",
  "Objective Pulse Defend": "GainExperienc_experience_id_556",
  "Objective Pulse Capture": "GainExperienc_experience_id_557",
  "Halloween Event NPC GreatP: Kill": "GainExperienc_experience_id_558",
  "Pumpkin Kill by Valkyrie Gunner": "GainExperienc_experience_id_559",
  "Pumpkin Kill by Sunderer Gunner": "GainExperienc_experience_id_560",
  "Pumpkin Kill by Magrider Gunner": "GainExperienc_experience_id_561",
  "Pumpkin Kill by Vanguard Gunner": "GainExperienc_experience_id_562",
  "Pumpkin Kill by Prowler Gunner": "GainExperienc_experience_id_563",
  "Pumpkin Kill by Liberator Gunner": "GainExperienc_experience_id_564",
  "Pumpkin Kill by Galaxy Gunner": "GainExperienc_experience_id_565",
  "Pumpkin Kill by Harasser Gunner": "GainExperienc_experience_id_566",
  "GPumpkin Kill by Sunder Gunner": "GainExperienc_experience_id_567",
  "GPumpkin Kill by Mag Gunner": "GainExperienc_experience_id_568",
  "GPumpkin Kill by Vang Gunner": "GainExperienc_experience_id_569",
  "GPumpkin Kill by Prow Gunner": "GainExperienc_experience_id_570",
  "GPumpkin Kill by Lib Gunner": "GainExperienc_experience_id_571",
  "GPumpkin Kill by Gal Gunner": "GainExperienc_experience_id_572",
  "GPumpkin Kill by Haras Gunner": "GainExperienc_experience_id_573",
  "Halloween Event NPC: Kill": "GainExperienc_experience_id_574",
  "Harasser Kill by Valkyrie Gunner": "GainExperienc_experience_id_575",
  "Valkyrie Kill by Harasser Gunner": "GainExperienc_experience_id_576",
  "Snowman kill by squad member": "GainExperienc_experience_id_577",
  "Gsnowman kill by squad member": "GainExperienc_experience_id_578",
  "Destroy Spitfire Turret": "GainExperienc_experience_id_579",
  "Vehicle Ram Kill - Spitfire Turret": "GainExperienc_experience_id_580",
  "Vehicle Repair - Spitfire Turret": "GainExperienc_experience_id_581",
  "Kill Assist - Spitfire Turret": "GainExperienc_experience_id_582",
  "Squad Repair - Spitfire Turret": "GainExperienc_experience_id_584",
  "Spot Kill - Spitfire Turret": "GainExperienc_experience_id_585",
  "Squad Spot Kill - Spitfire Turret": "GainExperienc_experience_id_586",
  "Kill Dummy NPC": "GainExperienc_experience_id_591",
  "Savior Kill (MAX)": "GainExperienc_experience_id_592",
  "Bounty Kill Bonus": "GainExperienc_experience_id_593",
  "Bounty Kill Cashed In": "GainExperienc_experience_id_594",
  "Bounty Kill Streak": "GainExperienc_experience_id_595",
  "Membership bonus xp": "GainExperienc_experience_id_596",
  "Victory Point XP": "GainExperienc_experience_id_597",
  "Continent Capture XP": "GainExperienc_experience_id_598",
  "Victory Point XP (-25%XP)": "GainExperienc_experience_id_599",
  "Victory Point XP (-50%XP)": "GainExperienc_experience_id_600",
  "Victory Point XP (-75%XP)": "GainExperienc_experience_id_601",
  "Victory Point XP (+50%XP)": "GainExperienc_experience_id_602",
  "Vehicle Ram Kill - Construction - Med": "GainExperienc_experience_id_603",
  "Kill/Destroy - Construction - Med": "GainExperienc_experience_id_604",
  "SquadRepair - Construction - Med": "GainExperienc_experience_id_605",
  "Repair - Construction - Med": "GainExperienc_experience_id_606",
  "KillAssist - Construction - Med": "GainExperienc_experience_id_607",
  "Spot Kill - Construction - Med ": "GainExperienc_experience_id_609",
  "Squad Spot Kill - Construction - Med": "GainExperienc_experience_id_610",
  "Vehicle Ram Kill - Construction - Small": "GainExperienc_experience_id_615",
  "Kill/Destroy - Construction - Small": "GainExperienc_experience_id_616",
  "SquadRepair - Construction - Sma": "GainExperienc_experience_id_617",
  "Repair - Construction - Small": "GainExperienc_experience_id_618",
  "KillAssist - Construction - Small": "GainExperienc_experience_id_619",
  "Spot Kill - Construction - Small ": "GainExperienc_experience_id_621",
  "Squad Spot Kill - Construction - Small": "GainExperienc_experience_id_622",
  "Vehicle Ram Kill - Construction - Large": "GainExperienc_experience_id_627",
  "Kill/Destroy - Construction - Large": "GainExperienc_experience_id_628",
  "SquadRepair - Construction - Lar": "GainExperienc_experience_id_629",
  "Repair - Construction - Large": "GainExperienc_experience_id_630",
  "KillAssist - Construction - Large": "GainExperienc_experience_id_631",
  "Spot Kill - Construction - Large ": "GainExperienc_experience_id_633",
  "Squad Spot Kill - Construction - Large": "GainExperienc_experience_id_634",
  "Vehicle Ram Kill - Construction - Core": "GainExperienc_experience_id_639",
  "Kill/Destroy - Construction - Core": "GainExperienc_experience_id_640",
  "SquadRepair - Construction - Cor": "GainExperienc_experience_id_641",
  "Repair - Construction - Core": "GainExperienc_experience_id_642",
  "KillAssist - Construction - Core": "GainExperienc_experience_id_643",
  "Spot Kill - Construction - Core ": "GainExperienc_experience_id_645",
  "Squad Spot Kill - Construction - Core": "GainExperienc_experience_id_646",
  "Vehicle Destruction - ANT": "GainExperienc_experience_id_651",
  "Vehicle Ram Kill - ANT": "GainExperienc_experience_id_652",
  "Vehicle Repair - ANT": "GainExperienc_experience_id_653",
  "Kill Assist - ANT": "GainExperienc_experience_id_654",
  "Squad Repair - ANT": "GainExperienc_experience_id_656",
  "ANT Kill by ANT Gunner": "GainExperienc_experience_id_657",
  "ANT Kill by Magrider Gunner": "GainExperienc_experience_id_658",
  "ANT Kill by Vanguard Gunner": "GainExperienc_experience_id_659",
  "ANT Kill by Prowler Gunner": "GainExperienc_experience_id_660",
  "ANT Kill by Lib Gunner": "GainExperienc_experience_id_661",
  "ANT Kill by Galaxy Gunner": "GainExperienc_experience_id_662",
  "Spot Kill - ANT": "GainExperienc_experience_id_663",
  "Squad Spot Kill - ANT": "GainExperienc_experience_id_664",
  "ANT Damage (Infantry vs Vehicle)": "GainExperienc_experience_id_665",
  "ANT Kill by Harasser Gunner": "GainExperienc_experience_id_666",
  "ANT Kill by Valkyrie Gunner": "GainExperienc_experience_id_671",
  "Chain Expl Assist: ANT": "GainExperienc_experience_id_672",
  "Bounty Kill Cashed In": "GainExperienc_experience_id_673",
  "Cortium Harvest": "GainExperienc_experience_id_674",
  "Cortium Deposit": "GainExperienc_experience_id_675",
  "Flash Kill by ANT Gunner": "GainExperienc_experience_id_676",
  "Galaxy Kill by ANT Gunner": "GainExperienc_experience_id_677",
  "Harasser Kill by ANT Gunner": "GainExperienc_experience_id_678",
  "Magrider Kill by ANT Gunner": "GainExperienc_experience_id_679",
  "Mosquito Kill by ANT Gunner": "GainExperienc_experience_id_680",
  "Player Kill by ANT Gunner": "GainExperienc_experience_id_681",
  "Prowler Kill by ANT Gunner": "GainExperienc_experience_id_682",
  "Pumpkin Kill by ANT Gunner": "GainExperienc_experience_id_683",
  "R Drone Kill by ANT Gunner": "GainExperienc_experience_id_684",
  "Reaver Kill by ANT Gunner": "GainExperienc_experience_id_685",
  "Scythe Kill by ANT Gunner": "GainExperienc_experience_id_686",
  "Snowman Kill by ANT Gunner": "GainExperienc_experience_id_687",
  "Sunderer Kill by ANT Gunner": "GainExperienc_experience_id_688",
  "Valkyrie Kill by ANT Gunner": "GainExperienc_experience_id_689",
  "Vanguard Kill by ANT Gunner": "GainExperienc_experience_id_690",
  "Kill Player - HIVE XP (Source)": "GainExperienc_experience_id_693",
  "Kill Player - HIVE XP (Target)": "GainExperienc_experience_id_694",
  "Kill Player Assist HIVE: Source": "GainExperienc_experience_id_695",
  "Kill Spawn Ass HIVE: Source": "GainExperienc_experience_id_696",
  "Heal Player HIVE: Source": "GainExperienc_experience_id_697",
  "MAX Repair HIVE: Source": "GainExperienc_experience_id_698",
  "Revive HIVE: Source": "GainExperienc_experience_id_699",
  "Destroy SecObj HIVE: Source": "GainExperienc_experience_id_701",
  "Destroy SecAss HIVE: Source": "GainExperienc_experience_id_702",
  "Vehicle Dest: Flash HIVE: Source": "GainExperienc_experience_id_703",
  "Transport Assist HIVE: Source": "GainExperienc_experience_id_705",
  "Vehicle Repair - Flash HIVE: Source": "GainExperienc_experience_id_706",
  "Resupply Player HIVE: Source": "GainExperienc_experience_id_707",
  "Kill Player Assist HIVE XP (Target)": "GainExperienc_experience_id_708",
  "Kill Spawn Ass HIVE XP (Target)": "GainExperienc_experience_id_709",
  "Heal Player HIVE XP (Target)": "GainExperienc_experience_id_710",
  "MAX Repair HIVE XP (Target)": "GainExperienc_experience_id_711",
  "Revive HIVE XP (Target)": "GainExperienc_experience_id_712",
  "Destroy SecObj HIVE XP (Target)": "GainExperienc_experience_id_714",
  "Destroy SecAss HIVE XP (Target)": "GainExperienc_experience_id_715",
  "Vehicle Dest: Flash HIVE XP (Target)": "GainExperienc_experience_id_716",
  "Transport Assist HIVE XP (Target)": "GainExperienc_experience_id_718",
  "Vehicle Repair - Flash HIVE XP (Target)": "GainExperienc_experience_id_719",
  "Resupply Player HIVE XP (Target)": "GainExperienc_experience_id_720",
  "Destroy Engineer Turret HIVE XP (Source)": "GainExperienc_experience_id_721",
  "Vehicle Destruction - Phalanx HIVE XP (Source)": "GainExperienc_experience_id_722",
  "Vehicle Destruction - Drop Pod HIVE XP (Source)": "GainExperienc_experience_id_723",
  "Vehicle Destruction - Galaxy HIVE XP (Source)": "GainExperienc_experience_id_724",
  "Vehicle Destruction - Liberator HIVE XP (Source)": "GainExperienc_experience_id_725",
  "Vehicle Destruction - Lightning HIVE XP (Source)": "GainExperienc_experience_id_726",
  "Vehicle Destruction - Magrider HIVE XP (Source)": "GainExperienc_experience_id_727",
  "Vehicle Destruction - Mosquito HIVE XP (Source)": "GainExperienc_experience_id_728",
  "Vehicle Destruction - Prowler HIVE XP (Source)": "GainExperienc_experience_id_729",
  "Vehicle Destruction - Reaver HIVE XP (Source)": "GainExperienc_experience_id_730",
  "Vehicle Destruction - Scythe HIVE XP (Source)": "GainExperienc_experience_id_731",
  "Vehicle Destruction - Sunderer HIVE XP (Source)": "GainExperienc_experience_id_732",
  "Vehicle Destruction - Vanguard HIVE XP (Source)": "GainExperienc_experience_id_733",
  "Vehicle Repair - Engi Turret HIVE XP (Source)": "GainExperienc_experience_id_734",
  "Vehicle Repair - Phalanx HIVE XP (Source)": "GainExperienc_experience_id_735",
  "Vehicle Repair - Drop Pod HIVE XP (Source)": "GainExperienc_experience_id_736",
  "Vehicle Repair - Galaxy HIVE XP (Source)": "GainExperienc_experience_id_737",
  "Vehicle Repair - Liberator HIVE XP (Source)": "GainExperienc_experience_id_738",
  "Vehicle Repair - Lightning HIVE XP (Source)": "GainExperienc_experience_id_739",
  "Vehicle Repair - Magrider HIVE XP (Source)": "GainExperienc_experience_id_740",
  "Destroy Engineer Turret HIVE XP (Target)": "GainExperienc_experience_id_741",
  "Vehicle Destruction - Phalanx HIVE XP (Target)": "GainExperienc_experience_id_742",
  "Vehicle Destruction - Drop Pod HIVE XP (Target)": "GainExperienc_experience_id_743",
  "Vehicle Destruction - Galaxy HIVE XP (Target)": "GainExperienc_experience_id_744",
  "Vehicle Destruction - Liberator HIVE XP (Target)": "GainExperienc_experience_id_745",
  "Vehicle Destruction - Lightning HIVE XP (Target)": "GainExperienc_experience_id_746",
  "Vehicle Destruction - Magrider HIVE XP (Target)": "GainExperienc_experience_id_747",
  "Vehicle Destruction - Mosquito HIVE XP (Target)": "GainExperienc_experience_id_748",
  "Vehicle Destruction - Prowler HIVE XP (Target)": "GainExperienc_experience_id_749",
  "Vehicle Destruction - Reaver HIVE XP (Target)": "GainExperienc_experience_id_750",
  "Vehicle Destruction - Scythe HIVE XP (Target)": "GainExperienc_experience_id_751",
  "Vehicle Destruction - Sunderer HIVE XP (Target)": "GainExperienc_experience_id_752",
  "Vehicle Destruction - Vanguard HIVE XP (Target)": "GainExperienc_experience_id_753",
  "Vehicle Repair - Engi Turret HIVE XP (Target)": "GainExperienc_experience_id_754",
  "Vehicle Repair - Phalanx HIVE XP (Target)": "GainExperienc_experience_id_755",
  "Vehicle Repair - Drop Pod HIVE XP (Target)": "GainExperienc_experience_id_756",
  "Vehicle Repair - Galaxy HIVE XP (Target)": "GainExperienc_experience_id_757",
  "Vehicle Repair - Liberator HIVE XP (Target)": "GainExperienc_experience_id_758",
  "Vehicle Repair - Lightning HIVE XP (Target)": "GainExperienc_experience_id_759",
  "Vehicle Repair - Magrider HIVE XP (Target)": "GainExperienc_experience_id_760",
  "Vehicle Repair - Mosquito HIVE XP (Source)": "GainExperienc_experience_id_761",
  "Vehicle Repair - Prowler HIVE XP (Source)": "GainExperienc_experience_id_762",
  "Vehicle Repair - Reaver HIVE XP (Source)": "GainExperienc_experience_id_763",
  "Vehicle Repair - Scythe HIVE XP (Source)": "GainExperienc_experience_id_764",
  "Vehicle Repair - Sunderer HIVE XP (Source)": "GainExperienc_experience_id_765",
  "Vehicle Repair - Vanguard HIVE XP (Source)": "GainExperienc_experience_id_766",
  "Kill Assist - Flash HIVE XP (Source)": "GainExperienc_experience_id_767",
  "Kill Assist - Engi Turret HIVE XP (Source)": "GainExperienc_experience_id_768",
  "Kill Assist - Phalanx HIVE XP (Source)": "GainExperienc_experience_id_769",
  "Kill Assist - Drop Pod HIVE XP (Source)": "GainExperienc_experience_id_770",
  "Kill Assist - Galaxy HIVE XP (Source)": "GainExperienc_experience_id_771",
  "Kill Assist - Liberator HIVE XP (Source)": "GainExperienc_experience_id_772",
  "Kill Assist - Lightning HIVE XP (Source)": "GainExperienc_experience_id_773",
  "Kill Assist - Magrider HIVE XP (Source)": "GainExperienc_experience_id_774",
  "Kill Assist - Mosquito HIVE XP (Source)": "GainExperienc_experience_id_775",
  "Kill Assist - Prowler HIVE XP (Source)": "GainExperienc_experience_id_776",
  "Kill Assist - Reaver HIVE XP (Source)": "GainExperienc_experience_id_777",
  "Kill Assist - Scythe HIVE XP (Source)": "GainExperienc_experience_id_778",
  "Kill Assist - Sunderer HIVE XP (Source)": "GainExperienc_experience_id_779",
  "Kill Assist - Vanguard HIVE XP (Source)": "GainExperienc_experience_id_780",
  "Vehicle Repair - Mosquito HIVE XP (Target)": "GainExperienc_experience_id_781",
  "Vehicle Repair - Prowler HIVE XP (Target)": "GainExperienc_experience_id_782",
  "Vehicle Repair - Reaver HIVE XP (Target)": "GainExperienc_experience_id_783",
  "Vehicle Repair - Scythe HIVE XP (Target)": "GainExperienc_experience_id_784",
  "Vehicle Repair - Sunderer HIVE XP (Target)": "GainExperienc_experience_id_785",
  "Vehicle Repair - Vanguard HIVE XP (Target)": "GainExperienc_experience_id_786",
  "Kill Assist - Flash HIVE XP (Target)": "GainExperienc_experience_id_787",
  "Kill Assist - Engi Turret HIVE XP (Target)": "GainExperienc_experience_id_788",
  "Kill Assist - Phalanx HIVE XP (Target)": "GainExperienc_experience_id_789",
  "Kill Assist - Drop Pod HIVE XP (Target)": "GainExperienc_experience_id_790",
  "Kill Assist - Galaxy HIVE XP (Target)": "GainExperienc_experience_id_791",
  "Kill Assist - Liberator HIVE XP (Target)": "GainExperienc_experience_id_792",
  "Kill Assist - Lightning HIVE XP (Target)": "GainExperienc_experience_id_793",
  "Kill Assist - Magrider HIVE XP (Target)": "GainExperienc_experience_id_794",
  "Kill Assist - Mosquito HIVE XP (Target)": "GainExperienc_experience_id_795",
  "Kill Assist - Prowler HIVE XP (Target)": "GainExperienc_experience_id_796",
  "Kill Assist - Reaver HIVE XP (Target)": "GainExperienc_experience_id_797",
  "Kill Assist - Scythe HIVE XP (Target)": "GainExperienc_experience_id_798",
  "Kill Assist - Sunderer HIVE XP (Target)": "GainExperienc_experience_id_799",
  "Kill Assist - Vanguard HIVE XP (Target)": "GainExperienc_experience_id_800",
  "Drop Pod Kill HIVE XP (Source)": "GainExperienc_experience_id_815",
  "Player Kill by Sunderer Gunner HIVE XP (Source)": "GainExperienc_experience_id_816",
  "Player Kill by Magrider Gunner HIVE XP (Source)": "GainExperienc_experience_id_817",
  "Player Kill by Vanguard Gunner HIVE XP (Source)": "GainExperienc_experience_id_818",
  "Player Kill by Prowler Gunner HIVE XP (Source)": "GainExperienc_experience_id_819",
  "Player Kill by Liberator Gunner HIVE XP (Source)": "GainExperienc_experience_id_820",
  "Drop Pod Kill HIVE XP (Target)": "GainExperienc_experience_id_835",
  "Player Kill by Sunderer Gunner HIVE XP (Target)": "GainExperienc_experience_id_836",
  "Player Kill by Magrider Gunner HIVE XP (Target)": "GainExperienc_experience_id_837",
  "Player Kill by Vanguard Gunner HIVE XP (Target)": "GainExperienc_experience_id_838",
  "Player Kill by Prowler Gunner HIVE XP (Target)": "GainExperienc_experience_id_839",
  "Player Kill by Liberator Gunner HIVE XP (Target)": "GainExperienc_experience_id_840",
  "Player Kill by Galaxy Gunner HIVE XP (Source)": "GainExperienc_experience_id_841",
  "Flash Kill by Sunderer Gunner HIVE XP (Source)": "GainExperienc_experience_id_842",
  "Sunderer Kill by Sunderer Gunner HIVE XP (Source)": "GainExperienc_experience_id_843",
  "Lightning Kill by Sunderer Gunne HIVE XP (Source)": "GainExperienc_experience_id_844",
  "Magrider Kill by Sunderer Gunner HIVE XP (Source)": "GainExperienc_experience_id_845",
  "Vanguard Kill by Sunderer Gunner HIVE XP (Source)": "GainExperienc_experience_id_846",
  "Prowler Kill by Sunderer Gunner HIVE XP (Source)": "GainExperienc_experience_id_847",
  "Scythe Kill by Sunderer Gunner HIVE XP (Source)": "GainExperienc_experience_id_848",
  "Reaver Kill by Sunderer Gunner HIVE XP (Source)": "GainExperienc_experience_id_849",
  "Mosquito Kill by Sunderer Gunner HIVE XP (Source)": "GainExperienc_experience_id_850",
  "Lib Kill by Sunderer HIVE XP (Source)": "GainExperienc_experience_id_851",
  "Galaxy Kill by Sunderer Gunner HIVE XP (Source)": "GainExperienc_experience_id_852",
  "Flash Kill by Magrider Gunner HIVE XP (Source)": "GainExperienc_experience_id_853",
  "Sunderer Kill by Magrider Gunner HIVE XP (Source)": "GainExperienc_experience_id_854",
  "Lightning Kill by Magrider Gunne HIVE XP (Source)": "GainExperienc_experience_id_855",
  "Vanguard Kill by Magrider Gunner HIVE XP (Source)": "GainExperienc_experience_id_856",
  "Prowler Kill by Magrider Gunner HIVE XP (Source)": "GainExperienc_experience_id_857",
  "Reaver Kill by Magrider Gunner HIVE XP (Source)": "GainExperienc_experience_id_858",
  "Mosquito Kill by Magrider Gunner HIVE XP (Source)": "GainExperienc_experience_id_859",
  "Lib Kill by Magrider HIVE XP (Source)": "GainExperienc_experience_id_860",
  "Player Kill by Galaxy Gunner HIVE XP (Target)": "GainExperienc_experience_id_861",
  "Flash Kill by Sunderer Gunner HIVE XP (Target)": "GainExperienc_experience_id_862",
  "Sunderer Kill by Sunderer Gunner HIVE XP (Target)": "GainExperienc_experience_id_863",
  "Lightning Kill by Sunderer Gunne HIVE XP (Target)": "GainExperienc_experience_id_864",
  "Magrider Kill by Sunderer Gunner HIVE XP (Target)": "GainExperienc_experience_id_865",
  "Vanguard Kill by Sunderer Gunner HIVE XP (Target)": "GainExperienc_experience_id_866",
  "Prowler Kill by Sunderer Gunner HIVE XP (Target)": "GainExperienc_experience_id_867",
  "Scythe Kill by Sunderer Gunner HIVE XP (Target)": "GainExperienc_experience_id_868",
  "Reaver Kill by Sunderer Gunner HIVE XP (Target)": "GainExperienc_experience_id_869",
  "Mosquito Kill by Sunderer Gunner HIVE XP (Target)": "GainExperienc_experience_id_870",
  "Lib Kill by Sunderer HIVE XP (Target)": "GainExperienc_experience_id_871",
  "Galaxy Kill by Sunderer Gunner HIVE XP (Target)": "GainExperienc_experience_id_872",
  "Flash Kill by Magrider Gunner HIVE XP (Target)": "GainExperienc_experience_id_873",
  "Sunderer Kill by Magrider Gunner HIVE XP (Target)": "GainExperienc_experience_id_874",
  "Lightning Kill by Magrider Gunne HIVE XP (Target)": "GainExperienc_experience_id_875",
  "Vanguard Kill by Magrider Gunner HIVE XP (Target)": "GainExperienc_experience_id_876",
  "Prowler Kill by Magrider Gunner HIVE XP (Target)": "GainExperienc_experience_id_877",
  "Reaver Kill by Magrider Gunner HIVE XP (Target)": "GainExperienc_experience_id_878",
  "Mosquito Kill by Magrider Gunner HIVE XP (Target)": "GainExperienc_experience_id_879",
  "Lib Kill by Magrider HIVE XP (Target)": "GainExperienc_experience_id_880",
  "Galaxy Kill by Magrider Gunner HIVE XP (Source)": "GainExperienc_experience_id_881",
  "Flash Kill by Vanguard Gunner HIVE XP (Source)": "GainExperienc_experience_id_882",
  "Sunderer Kill by Vanguard Gunner HIVE XP (Source)": "GainExperienc_experience_id_883",
  "Lightning Kill by Vanguard Gunne HIVE XP (Source)": "GainExperienc_experience_id_884",
  "Magrider Kill by Vanguard Gunner HIVE XP (Source)": "GainExperienc_experience_id_885",
  "Prowler Kill by Vanguard Gunner HIVE XP (Source)": "GainExperienc_experience_id_886",
  "Scythe Kill by Vanguard Gunner HIVE XP (Source)": "GainExperienc_experience_id_887",
  "Mosquito Kill by Vanguard Gunner HIVE XP (Source)": "GainExperienc_experience_id_888",
  "Lib Kill by Vanguard HIVE XP (Source)": "GainExperienc_experience_id_889",
  "Galaxy Kill by Vanguard Gunner HIVE XP (Source)": "GainExperienc_experience_id_890",
  "Flash Kill by Prowler Gunner HIVE XP (Source)": "GainExperienc_experience_id_891",
  "Sunderer Kill by Prowler Gunner HIVE XP (Source)": "GainExperienc_experience_id_892",
  "Lightning Kill by Prowler Gunner HIVE XP (Source)": "GainExperienc_experience_id_893",
  "Magrider Kill by Prowler Gunner HIVE XP (Source)": "GainExperienc_experience_id_894",
  "Vanguard Kill by Prowler Gunner HIVE XP (Source)": "GainExperienc_experience_id_895",
  "Scythe Kill by Prowler Gunner HIVE XP (Source)": "GainExperienc_experience_id_896",
  "Reaver Kill by Prowler Gunner HIVE XP (Source)": "GainExperienc_experience_id_897",
  "Liberator Kill by Prowler Gunner HIVE XP (Source)": "GainExperienc_experience_id_898",
  "Galaxy Kill by Prowler Gunner HIVE XP (Source)": "GainExperienc_experience_id_899",
  "Galaxy Kill by Magrider Gunner HIVE XP (Target)": "GainExperienc_experience_id_900",
  "Flash Kill by Vanguard Gunner HIVE XP (Target)": "GainExperienc_experience_id_901",
  "Sunderer Kill by Vanguard Gunner HIVE XP (Target)": "GainExperienc_experience_id_902",
  "Lightning Kill by Vanguard Gunne HIVE XP (Target)": "GainExperienc_experience_id_903",
  "Magrider Kill by Vanguard Gunner HIVE XP (Target)": "GainExperienc_experience_id_904",
  "Prowler Kill by Vanguard Gunner HIVE XP (Target)": "GainExperienc_experience_id_905",
  "Scythe Kill by Vanguard Gunner HIVE XP (Target)": "GainExperienc_experience_id_906",
  "Mosquito Kill by Vanguard Gunner HIVE XP (Target)": "GainExperienc_experience_id_907",
  "Lib Kill by Vanguard HIVE XP (Target)": "GainExperienc_experience_id_908",
  "Galaxy Kill by Vanguard Gunner HIVE XP (Target)": "GainExperienc_experience_id_909",
  "Flash Kill by Prowler Gunner HIVE XP (Target)": "GainExperienc_experience_id_910",
  "Sunderer Kill by Prowler Gunner HIVE XP (Target)": "GainExperienc_experience_id_911",
  "Lightning Kill by Prowler Gunner HIVE XP (Target)": "GainExperienc_experience_id_912",
  "Magrider Kill by Prowler Gunner HIVE XP (Target)": "GainExperienc_experience_id_913",
  "Vanguard Kill by Prowler Gunner HIVE XP (Target)": "GainExperienc_experience_id_914",
  "Scythe Kill by Prowler Gunner HIVE XP (Target)": "GainExperienc_experience_id_915",
  "Reaver Kill by Prowler Gunner HIVE XP (Target)": "GainExperienc_experience_id_916",
  "Liberator Kill by Prowler Gunner HIVE XP (Target)": "GainExperienc_experience_id_917",
  "Galaxy Kill by Prowler Gunner HIVE XP (Target)": "GainExperienc_experience_id_918",
  "Flash Kill by Liberator Gunner HIVE XP (Source)": "GainExperienc_experience_id_919",
  "Sunderer Kill by Lib Gunner HIVE XP (Source)": "GainExperienc_experience_id_920",
  "Lightning Kill by Liberator Gunn HIVE XP (Source)": "GainExperienc_experience_id_921",
  "Magrider Kill by Lib Gunner HIVE XP (Source)": "GainExperienc_experience_id_922",
  "Vanguard Kill by Lib Gunner HIVE XP (Source)": "GainExperienc_experience_id_923",
  "Prowler Kill by Liberator Gunner HIVE XP (Source)": "GainExperienc_experience_id_924",
  "Scythe Kill by Liberator Gunner HIVE XP (Source)": "GainExperienc_experience_id_925",
  "Reaver Kill by Liberator Gunner HIVE XP (Source)": "GainExperienc_experience_id_926",
  "Mosquito Kill by Lib Gunner HIVE XP (Source)": "GainExperienc_experience_id_927",
  "Lib Kill by Liberator HIVE XP (Source)": "GainExperienc_experience_id_928",
  "Galaxy Kill by Liberator Gunner HIVE XP (Source)": "GainExperienc_experience_id_929",
  "Flash Kill by Galaxy Gunner HIVE XP (Source)": "GainExperienc_experience_id_930",
  "Sunderer Kill by Galaxy Gunner HIVE XP (Source)": "GainExperienc_experience_id_931",
  "Lightning Kill by Galaxy Gunner HIVE XP (Source)": "GainExperienc_experience_id_932",
  "Magrider Kill by Galaxy Gunner HIVE XP (Source)": "GainExperienc_experience_id_933",
  "Vanguard Kill by Galaxy Gunner HIVE XP (Source)": "GainExperienc_experience_id_934",
  "Prowler Kill by Galaxy Gunner HIVE XP (Source)": "GainExperienc_experience_id_935",
  "Scythe Kill by Galaxy Gunner HIVE XP (Source)": "GainExperienc_experience_id_936",
  "Reaver Kill by Galaxy Gunner HIVE XP (Source)": "GainExperienc_experience_id_937",
  "Mosquito Kill by Galaxy Gunner HIVE XP (Source)": "GainExperienc_experience_id_938",
  "Flash Kill by Liberator Gunner HIVE XP (Target)": "GainExperienc_experience_id_939",
  "Sunderer Kill by Lib Gunner HIVE XP (Target)": "GainExperienc_experience_id_940",
  "Lightning Kill by Liberator Gunn HIVE XP (Target)": "GainExperienc_experience_id_941",
  "Magrider Kill by Lib Gunner HIVE XP (Target)": "GainExperienc_experience_id_942",
  "Vanguard Kill by Lib Gunner HIVE XP (Target)": "GainExperienc_experience_id_943",
  "Prowler Kill by Liberator Gunner HIVE XP (Target)": "GainExperienc_experience_id_944",
  "Scythe Kill by Liberator Gunner HIVE XP (Target)": "GainExperienc_experience_id_945",
  "Reaver Kill by Liberator Gunner HIVE XP (Target)": "GainExperienc_experience_id_946",
  "Mosquito Kill by Lib Gunner HIVE XP (Target)": "GainExperienc_experience_id_947",
  "Lib Kill by Liberator HIVE XP (Target)": "GainExperienc_experience_id_948",
  "Galaxy Kill by Liberator Gunner HIVE XP (Target)": "GainExperienc_experience_id_949",
  "Flash Kill by Galaxy Gunner HIVE XP (Target)": "GainExperienc_experience_id_950",
  "Sunderer Kill by Galaxy Gunner HIVE XP (Target)": "GainExperienc_experience_id_951",
  "Lightning Kill by Galaxy Gunner HIVE XP (Target)": "GainExperienc_experience_id_952",
  "Magrider Kill by Galaxy Gunner HIVE XP (Target)": "GainExperienc_experience_id_953",
  "Vanguard Kill by Galaxy Gunner HIVE XP (Target)": "GainExperienc_experience_id_954",
  "Prowler Kill by Galaxy Gunner HIVE XP (Target)": "GainExperienc_experience_id_955",
  "Scythe Kill by Galaxy Gunner HIVE XP (Target)": "GainExperienc_experience_id_956",
  "Reaver Kill by Galaxy Gunner HIVE XP (Target)": "GainExperienc_experience_id_957",
  "Mosquito Kill by Galaxy Gunner HIVE XP (Target)": "GainExperienc_experience_id_958",
  "LibKill by Galaxy Gunner HIVE XP (Source)": "GainExperienc_experience_id_959",
  "Galaxy Kill by Galaxy Gunner HIVE XP (Source)": "GainExperienc_experience_id_960",
  "Terminal Kill HIVE XP (Source)": "GainExperienc_experience_id_961",
  "Terminal Repair HIVE XP (Source)": "GainExperienc_experience_id_962",
  "Galaxy Damage HIVE XP (Source)": "GainExperienc_experience_id_966",
  "Liberator Damage HIVE XP (Source)": "GainExperienc_experience_id_967",
  "Mosquito Damage HIVE XP (Source)": "GainExperienc_experience_id_969",
  "Reaver Damage HIVE XP (Source)": "GainExperienc_experience_id_970",
  "Scythe Damage HIVE XP (Source)": "GainExperienc_experience_id_971",
  "Vehicle Repair - Harasser HIVE XP (Source)": "GainExperienc_experience_id_974",
  "Kill Assist - Harasser HIVE XP (Source)": "GainExperienc_experience_id_975",
  "Spot Kill - Harasser HIVE XP (Source)": "GainExperienc_experience_id_977",
  "LibKill by Galaxy Gunner HIVE XP (Target)": "GainExperienc_experience_id_978",
  "Galaxy Kill by Galaxy Gunner HIVE XP (Target)": "GainExperienc_experience_id_979",
  "Terminal Kill HIVE XP (Target)": "GainExperienc_experience_id_980",
  "Terminal Repair HIVE XP (Target)": "GainExperienc_experience_id_981",
  "Galaxy Damage HIVE XP (Target)": "GainExperienc_experience_id_985",
  "Liberator Damage HIVE XP (Target)": "GainExperienc_experience_id_986",
  "Mosquito Damage HIVE XP (Target)": "GainExperienc_experience_id_988",
  "Reaver Damage HIVE XP (Target)": "GainExperienc_experience_id_989",
  "Scythe Damage HIVE XP (Target)": "GainExperienc_experience_id_990",
  "Vehicle Repair - Harasser HIVE XP (Target)": "GainExperienc_experience_id_993",
  "Kill Assist - Harasser HIVE XP (Target)": "GainExperienc_experience_id_994",
  "Spot Kill - Harasser HIVE XP (Target)": "GainExperienc_experience_id_996",
  "Harasser Kill by Sunderer Gunne HIVE XP (Source)": "GainExperienc_experience_id_997",
  "Harasser Kill by Magrider Gunne HIVE XP (Source)": "GainExperienc_experience_id_998",
  "Harasser Kill by Vanguard Gunne HIVE XP (Source)": "GainExperienc_experience_id_999",
  "Harasser Kill by Prowler Gunner HIVE XP (Source)": "GainExperienc_experience_id_1000",
  "Harasser Kill by Liberator Gunn HIVE XP (Source)": "GainExperienc_experience_id_1001",
  "Harasser Kill by Galaxy Gunner HIVE XP (Source)": "GainExperienc_experience_id_1002",
  "Player Kill by Harasser Gunner HIVE XP (Source)": "GainExperienc_experience_id_1003",
  "Flash Kill by Harasser Gunner HIVE XP (Source)": "GainExperienc_experience_id_1004",
  "Sunderer Kill by Harasser Gunner HIVE XP (Source)": "GainExperienc_experience_id_1005",
  "Lightning Kill by Harasser Gunne HIVE XP (Source)": "GainExperienc_experience_id_1006",
  "Vanguard Kill by Harasser Gunner HIVE XP (Source)": "GainExperienc_experience_id_1007",
  "Prowler Kill by Harasser Gunner HIVE XP (Source)": "GainExperienc_experience_id_1008",
  "Reaver Kill by Harasser Gunner HIVE XP (Source)": "GainExperienc_experience_id_1009",
  "Mosquito Kill by Harasser Gunner HIVE XP (Source)": "GainExperienc_experience_id_1010",
  "Lib Kill by Harasser HIVE XP (Source)": "GainExperienc_experience_id_1011",
  "Galaxy Kill by Harasser Gunner HIVE XP (Source)": "GainExperienc_experience_id_1012",
  "Harasser Kill by Harasser Gunner HIVE XP (Source)": "GainExperienc_experience_id_1013",
  "Magrider Kill by Harasser Gunner HIVE XP (Source)": "GainExperienc_experience_id_1014",
  "Scythe Kill by Harasser Gunner HIVE XP (Source)": "GainExperienc_experience_id_1015",
  "Tank Mine Despawn/Defusal HIVE XP (Source)": "GainExperienc_experience_id_1016",
  "Harasser Kill by Sunderer Gunne HIVE XP (Target)": "GainExperienc_experience_id_1017",
  "Harasser Kill by Magrider Gunne HIVE XP (Target)": "GainExperienc_experience_id_1018",
  "Harasser Kill by Vanguard Gunne HIVE XP (Target)": "GainExperienc_experience_id_1019",
  "Harasser Kill by Prowler Gunner HIVE XP (Target)": "GainExperienc_experience_id_1020",
  "Harasser Kill by Liberator Gunn HIVE XP (Target)": "GainExperienc_experience_id_1021",
  "Harasser Kill by Galaxy Gunner HIVE XP (Target)": "GainExperienc_experience_id_1022",
  "Player Kill by Harasser Gunner HIVE XP (Target)": "GainExperienc_experience_id_1023",
  "Flash Kill by Harasser Gunner HIVE XP (Target)": "GainExperienc_experience_id_1024",
  "Sunderer Kill by Harasser Gunner HIVE XP (Target)": "GainExperienc_experience_id_1025",
  "Lightning Kill by Harasser Gunne HIVE XP (Target)": "GainExperienc_experience_id_1026",
  "Vanguard Kill by Harasser Gunner HIVE XP (Target)": "GainExperienc_experience_id_1027",
  "Prowler Kill by Harasser Gunner HIVE XP (Target)": "GainExperienc_experience_id_1028",
  "Reaver Kill by Harasser Gunner HIVE XP (Target)": "GainExperienc_experience_id_1029",
  "Mosquito Kill by Harasser Gunner HIVE XP (Target)": "GainExperienc_experience_id_1030",
  "Lib Kill by Harasser HIVE XP (Target)": "GainExperienc_experience_id_1031",
  "Galaxy Kill by Harasser Gunner HIVE XP (Target)": "GainExperienc_experience_id_1032",
  "Harasser Kill by Harasser Gunner HIVE XP (Target)": "GainExperienc_experience_id_1033",
  "Magrider Kill by Harasser Gunner HIVE XP (Target)": "GainExperienc_experience_id_1034",
  "Scythe Kill by Harasser Gunner HIVE XP (Target)": "GainExperienc_experience_id_1035",
  "Tank Mine Despawn/Defusal HIVE XP (Target)": "GainExperienc_experience_id_1036",
  "Vehicle Gunner Kill Share - Infantry HIVE XP (Source)": "GainExperienc_experience_id_1037",
  "Vehicle Gunner Kill Share - Flash HIVE XP (Source)": "GainExperienc_experience_id_1038",
  "Vehicle Gunner Kill Share - Engineer Turret HIVE XP (Source)": "GainExperienc_experience_id_1039",
  "Vehicle Gunner Kill Share - Phalanx HIVE XP (Source)": "GainExperienc_experience_id_1040",
  "Vehicle Gunner Kill Share - Drop Pod HIVE XP (Source)": "GainExperienc_experience_id_1041",
  "Vehicle Gunner Kill Share - Galaxy HIVE XP (Source)": "GainExperienc_experience_id_1042",
  "Vehicle Gunner Kill Share - Liberator HIVE XP (Source)": "GainExperienc_experience_id_1043",
  "Vehicle Gunner Kill Share - Lightning HIVE XP (Source)": "GainExperienc_experience_id_1044",
  "Vehicle Gunner Kill Share - Magrider HIVE XP (Source)": "GainExperienc_experience_id_1045",
  "Vehicle Gunner Kill Share - Mosquito HIVE XP (Source)": "GainExperienc_experience_id_1046",
  "Vehicle Gunner Kill Share - Prowler HIVE XP (Source)": "GainExperienc_experience_id_1047",
  "Vehicle Gunner Kill Share - Reaver HIVE XP (Source)": "GainExperienc_experience_id_1048",
  "Vehicle Gunner Kill Share - Scythe HIVE XP (Source)": "GainExperienc_experience_id_1049",
  "Vehicle Gunner Kill Share - Sunderer HIVE XP (Source)": "GainExperienc_experience_id_1050",
  "Vehicle Gunner Kill Share - Vanguard HIVE XP (Source)": "GainExperienc_experience_id_1051",
  "Vehicle Gunner Kill Share - Harasser HIVE XP (Source)": "GainExperienc_experience_id_1052",
  "Vehicle Gunner Kill Assist Share - Infantry HIVE XP (Source)": "GainExperienc_experience_id_1053",
  "Vehicle Gunner Kill Assist Share - Flash HIVE XP (Source)": "GainExperienc_experience_id_1054",
  "Vehicle Gunner Kill Assist Share - Engi Turret HIVE XP (Source)": "GainExperienc_experience_id_1055",
  "Vehicle Gunner Kill Assist Share - Phalanx HIVE XP (Source)": "GainExperienc_experience_id_1056",
  "Vehicle Gunner Kill Share - Infantry HIVE XP (Target)": "GainExperienc_experience_id_1057",
  "Vehicle Gunner Kill Share - Flash HIVE XP (Target)": "GainExperienc_experience_id_1058",
  "Vehicle Gunner Kill Share - Engineer Turret HIVE XP (Target)": "GainExperienc_experience_id_1059",
  "Vehicle Gunner Kill Share - Phalanx HIVE XP (Target)": "GainExperienc_experience_id_1060",
  "Vehicle Gunner Kill Share - Drop Pod HIVE XP (Target)": "GainExperienc_experience_id_1061",
  "Vehicle Gunner Kill Share - Galaxy HIVE XP (Target)": "GainExperienc_experience_id_1062",
  "Vehicle Gunner Kill Share - Liberator HIVE XP (Target)": "GainExperienc_experience_id_1063",
  "Vehicle Gunner Kill Share - Lightning HIVE XP (Target)": "GainExperienc_experience_id_1064",
  "Vehicle Gunner Kill Share - Magrider HIVE XP (Target)": "GainExperienc_experience_id_1065",
  "Vehicle Gunner Kill Share - Mosquito HIVE XP (Target)": "GainExperienc_experience_id_1066",
  "Vehicle Gunner Kill Share - Prowler HIVE XP (Target)": "GainExperienc_experience_id_1067",
  "Vehicle Gunner Kill Share - Reaver HIVE XP (Target)": "GainExperienc_experience_id_1068",
  "Vehicle Gunner Kill Share - Scythe HIVE XP (Target)": "GainExperienc_experience_id_1069",
  "Vehicle Gunner Kill Share - Sunderer HIVE XP (Target)": "GainExperienc_experience_id_1070",
  "Vehicle Gunner Kill Share - Vanguard HIVE XP (Target)": "GainExperienc_experience_id_1071",
  "Vehicle Gunner Kill Share - Harasser HIVE XP (Target)": "GainExperienc_experience_id_1072",
  "Vehicle Gunner Kill Assist Share - Infantry HIVE XP (Target)": "GainExperienc_experience_id_1073",
  "Vehicle Gunner Kill Assist Share - Flash HIVE XP (Target)": "GainExperienc_experience_id_1074",
  "Vehicle Gunner Kill Assist Share - Engi Turret HIVE XP (Target)": "GainExperienc_experience_id_1075",
  "Vehicle Gunner Kill Assist Share - Phalanx HIVE XP (Target)": "GainExperienc_experience_id_1076",
  "Vehicle Gunner Kill Assist Share - Drop Pod HIVE XP (Source)": "GainExperienc_experience_id_1077",
  "Vehicle Gunner Kill Assist Share - Galaxy HIVE XP (Source)": "GainExperienc_experience_id_1078",
  "Vehicle Gunner Kill Assist Share - Liberator HIVE XP (Source)": "GainExperienc_experience_id_1079",
  "Vehicle Gunner Kill Assist Share - Lightning HIVE XP (Source)": "GainExperienc_experience_id_1080",
  "Vehicle Gunner Kill Assist Share - Magrider HIVE XP (Source)": "GainExperienc_experience_id_1081",
  "Vehicle Gunner Kill Assist Share - Mosquito HIVE XP (Source)": "GainExperienc_experience_id_1082",
  "Vehicle Gunner Kill Assist Share - Prowler HIVE XP (Source)": "GainExperienc_experience_id_1083",
  "Vehicle Gunner Kill Assist Share - Reaver HIVE XP (Source)": "GainExperienc_experience_id_1084",
  "Vehicle Gunner Kill Assist Share - Scythe HIVE XP (Source)": "GainExperienc_experience_id_1085",
  "Vehicle Gunner Kill Assist Share - Sunderer HIVE XP (Source)": "GainExperienc_experience_id_1086",
  "Vehicle Gunner Kill Assist Share - Vanguard HIVE XP (Source)": "GainExperienc_experience_id_1087",
  "Vehicle Gunner Kill Assist Share - Harasser HIVE XP (Source)": "GainExperienc_experience_id_1088",
  "Vehicle Passenger Kill Share - Infantry HIVE XP (Source)": "GainExperienc_experience_id_1089",
  "Vehicle Passenger Kill Share - Flash HIVE XP (Source)": "GainExperienc_experience_id_1090",
  "Vehicle Passenger Kill Share - Engineer Turret HIVE XP (Source)": "GainExperienc_experience_id_1091",
  "Vehicle Passenger Kill Share - Phalanx HIVE XP (Source)": "GainExperienc_experience_id_1092",
  "Vehicle Passenger Kill Share - Drop Pod HIVE XP (Source)": "GainExperienc_experience_id_1093",
  "Vehicle Passenger Kill Share - Galaxy HIVE XP (Source)": "GainExperienc_experience_id_1094",
  "Vehicle Passenger Kill Share - Liberator HIVE XP (Source)": "GainExperienc_experience_id_1095",
  "Vehicle Passenger Kill Share - Lightning HIVE XP (Source)": "GainExperienc_experience_id_1096",
  "Vehicle Gunner Kill Assist Share - Drop Pod HIVE XP (Target)": "GainExperienc_experience_id_1097",
  "Vehicle Gunner Kill Assist Share - Galaxy HIVE XP (Target)": "GainExperienc_experience_id_1098",
  "Vehicle Gunner Kill Assist Share - Liberator HIVE XP (Target)": "GainExperienc_experience_id_1099",
  "Vehicle Gunner Kill Assist Share - Lightning HIVE XP (Target)": "GainExperienc_experience_id_1100",
  "Vehicle Gunner Kill Assist Share - Magrider HIVE XP (Target)": "GainExperienc_experience_id_1101",
  "Vehicle Gunner Kill Assist Share - Mosquito HIVE XP (Target)": "GainExperienc_experience_id_1102",
  "Vehicle Gunner Kill Assist Share - Prowler HIVE XP (Target)": "GainExperienc_experience_id_1103",
  "Vehicle Gunner Kill Assist Share - Reaver HIVE XP (Target)": "GainExperienc_experience_id_1104",
  "Vehicle Gunner Kill Assist Share - Scythe HIVE XP (Target)": "GainExperienc_experience_id_1105",
  "Vehicle Gunner Kill Assist Share - Sunderer HIVE XP (Target)": "GainExperienc_experience_id_1106",
  "Vehicle Gunner Kill Assist Share - Vanguard HIVE XP (Target)": "GainExperienc_experience_id_1107",
  "Vehicle Gunner Kill Assist Share - Harasser HIVE XP (Target)": "GainExperienc_experience_id_1108",
  "Vehicle Passenger Kill Share - Infantry HIVE XP (Target)": "GainExperienc_experience_id_1109",
  "Vehicle Passenger Kill Share - Flash HIVE XP (Target)": "GainExperienc_experience_id_1110",
  "Vehicle Passenger Kill Share - Engineer Turret HIVE XP (Target)": "GainExperienc_experience_id_1111",
  "Vehicle Passenger Kill Share - Phalanx HIVE XP (Target)": "GainExperienc_experience_id_1112",
  "Vehicle Passenger Kill Share - Drop Pod HIVE XP (Target)": "GainExperienc_experience_id_1113",
  "Vehicle Passenger Kill Share - Galaxy HIVE XP (Target)": "GainExperienc_experience_id_1114",
  "Vehicle Passenger Kill Share - Liberator HIVE XP (Target)": "GainExperienc_experience_id_1115",
  "Vehicle Passenger Kill Share - Lightning HIVE XP (Target)": "GainExperienc_experience_id_1116",
  "Vehicle Passenger Kill Share - Magrider HIVE XP (Source)": "GainExperienc_experience_id_1117",
  "Vehicle Passenger Kill Share - Mosquito HIVE XP (Source)": "GainExperienc_experience_id_1118",
  "Vehicle Passenger Kill Share - Prowler HIVE XP (Source)": "GainExperienc_experience_id_1119",
  "Vehicle Passenger Kill Share - Reaver HIVE XP (Source)": "GainExperienc_experience_id_1120",
  "Vehicle Passenger Kill Share - Scythe HIVE XP (Source)": "GainExperienc_experience_id_1121",
  "Vehicle Passenger Kill Share - Sunderer HIVE XP (Source)": "GainExperienc_experience_id_1122",
  "Vehicle Passenger Kill Share - Vanguard HIVE XP (Source)": "GainExperienc_experience_id_1123",
  "Vehicle Passenger Kill Share - Harasser HIVE XP (Source)": "GainExperienc_experience_id_1124",
  "Vehicle Driver Kill Assist Share - Infantry HIVE XP (Source)": "GainExperienc_experience_id_1125",
  "Vehicle Driver Kill Assist Share - Flash HIVE XP (Source)": "GainExperienc_experience_id_1126",
  "Vehicle Driver Kill Assist Share - Engi Turret HIVE XP (Source)": "GainExperienc_experience_id_1127",
  "Vehicle Driver Kill Assist Share - Phalanx HIVE XP (Source)": "GainExperienc_experience_id_1128",
  "Vehicle Driver Kill Assist Share - Drop Pod HIVE XP (Source)": "GainExperienc_experience_id_1129",
  "Vehicle Driver Kill Assist Share - Galaxy HIVE XP (Source)": "GainExperienc_experience_id_1130",
  "Vehicle Driver Kill Assist Share - Liberator HIVE XP (Source)": "GainExperienc_experience_id_1131",
  "Vehicle Driver Kill Assist Share - Lightning HIVE XP (Source)": "GainExperienc_experience_id_1132",
  "Vehicle Driver Kill Assist Share - Magrider HIVE XP (Source)": "GainExperienc_experience_id_1133",
  "Vehicle Driver Kill Assist Share - Mosquito HIVE XP (Source)": "GainExperienc_experience_id_1134",
  "Vehicle Driver Kill Assist Share - Prowler HIVE XP (Source)": "GainExperienc_experience_id_1135",
  "Vehicle Driver Kill Assist Share - Reaver HIVE XP (Source)": "GainExperienc_experience_id_1136",
  "Vehicle Passenger Kill Share - Magrider HIVE XP (Target)": "GainExperienc_experience_id_1137",
  "Vehicle Passenger Kill Share - Mosquito HIVE XP (Target)": "GainExperienc_experience_id_1138",
  "Vehicle Passenger Kill Share - Prowler HIVE XP (Target)": "GainExperienc_experience_id_1139",
  "Vehicle Passenger Kill Share - Reaver HIVE XP (Target)": "GainExperienc_experience_id_1140",
  "Vehicle Passenger Kill Share - Scythe HIVE XP (Target)": "GainExperienc_experience_id_1141",
  "Vehicle Passenger Kill Share - Sunderer HIVE XP (Target)": "GainExperienc_experience_id_1142",
  "Vehicle Passenger Kill Share - Vanguard HIVE XP (Target)": "GainExperienc_experience_id_1143",
  "Vehicle Passenger Kill Share - Harasser HIVE XP (Target)": "GainExperienc_experience_id_1144",
  "Vehicle Driver Kill Assist Share - Infantry HIVE XP (Target)": "GainExperienc_experience_id_1145",
  "Vehicle Driver Kill Assist Share - Flash HIVE XP (Target)": "GainExperienc_experience_id_1146",
  "Vehicle Driver Kill Assist Share - Engi Turret HIVE XP (Target)": "GainExperienc_experience_id_1147",
  "Vehicle Driver Kill Assist Share - Phalanx HIVE XP (Target)": "GainExperienc_experience_id_1148",
  "Vehicle Driver Kill Assist Share - Drop Pod HIVE XP (Target)": "GainExperienc_experience_id_1149",
  "Vehicle Driver Kill Assist Share - Galaxy HIVE XP (Target)": "GainExperienc_experience_id_1150",
  "Vehicle Driver Kill Assist Share - Liberator HIVE XP (Target)": "GainExperienc_experience_id_1151",
  "Vehicle Driver Kill Assist Share - Lightning HIVE XP (Target)": "GainExperienc_experience_id_1152",
  "Vehicle Driver Kill Assist Share - Magrider HIVE XP (Target)": "GainExperienc_experience_id_1153",
  "Vehicle Driver Kill Assist Share - Mosquito HIVE XP (Target)": "GainExperienc_experience_id_1154",
  "Vehicle Driver Kill Assist Share - Prowler HIVE XP (Target)": "GainExperienc_experience_id_1155",
  "Vehicle Driver Kill Assist Share - Reaver HIVE XP (Target)": "GainExperienc_experience_id_1156",
  "Vehicle Driver Kill Assist Share - Scythe HIVE XP (Source)": "GainExperienc_experience_id_1157",
  "Vehicle Driver Kill Assist Share - Sunderer HIVE XP (Source)": "GainExperienc_experience_id_1158",
  "Vehicle Driver Kill Assist Share - Vanguard HIVE XP (Source)": "GainExperienc_experience_id_1159",
  "Vehicle Driver Kill Assist Share - Harasser HIVE XP (Source)": "GainExperienc_experience_id_1160",
  "Valkyrie Kill by Sunderer Gunner HIVE XP (Source)": "GainExperienc_experience_id_1161",
  "Valkyrie Kill by Magrider Gunner HIVE XP (Source)": "GainExperienc_experience_id_1162",
  "Valkyrie Kill by Vanguard Gunner HIVE XP (Source)": "GainExperienc_experience_id_1163",
  "Valkyrie Kill by Prowler Gunner HIVE XP (Source)": "GainExperienc_experience_id_1164",
  "Valkyrie Kill by Liberator Gunner HIVE XP (Source)": "GainExperienc_experience_id_1165",
  "Valkyrie Kill by Galaxy Gunner HIVE XP (Source)": "GainExperienc_experience_id_1166",
  "Player Kill by Valkyrie Gunner HIVE XP (Source)": "GainExperienc_experience_id_1167",
  "Vehicle Gunner Kill Share - Valkyrie HIVE XP (Source)": "GainExperienc_experience_id_1168",
  "Vehicle Gunner Kill Assist Share - Valkyrie HIVE XP (Source)": "GainExperienc_experience_id_1169",
  "Vehicle Passenger Kill Share - Valkyrie HIVE XP (Source)": "GainExperienc_experience_id_1170",
  "Vehicle Driver Kill Assist Share - Valkyrie HIVE XP (Source)": "GainExperienc_experience_id_1171",
  "Flash Kill by Valkyrie Gunner HIVE XP (Source)": "GainExperienc_experience_id_1172",
  "Sunderer Kill by Valkyrie Gunner HIVE XP (Source)": "GainExperienc_experience_id_1173",
  "Lightning Kill by Valkyrie Gunne HIVE XP (Source)": "GainExperienc_experience_id_1174",
  "Vanguard Kill by Valkyrie Gunner HIVE XP (Source)": "GainExperienc_experience_id_1175",
  "Prowler Kill by Valkyrie Gunner HIVE XP (Source)": "GainExperienc_experience_id_1176",
  "Vehicle Driver Kill Assist Share - Scythe HIVE XP (Target)": "GainExperienc_experience_id_1177",
  "Vehicle Driver Kill Assist Share - Sunderer HIVE XP (Target)": "GainExperienc_experience_id_1178",
  "Vehicle Driver Kill Assist Share - Vanguard HIVE XP (Target)": "GainExperienc_experience_id_1179",
  "Vehicle Driver Kill Assist Share - Harasser HIVE XP (Target)": "GainExperienc_experience_id_1180",
  "Valkyrie Kill by Sunderer Gunner HIVE XP (Target)": "GainExperienc_experience_id_1181",
  "Valkyrie Kill by Magrider Gunner HIVE XP (Target)": "GainExperienc_experience_id_1182",
  "Valkyrie Kill by Vanguard Gunner HIVE XP (Target)": "GainExperienc_experience_id_1183",
  "Valkyrie Kill by Prowler Gunner HIVE XP (Target)": "GainExperienc_experience_id_1184",
  "Valkyrie Kill by Liberator Gunner HIVE XP (Target)": "GainExperienc_experience_id_1185",
  "Valkyrie Kill by Galaxy Gunner HIVE XP (Target)": "GainExperienc_experience_id_1186",
  "Player Kill by Valkyrie Gunner HIVE XP (Target)": "GainExperienc_experience_id_1187",
  "Vehicle Gunner Kill Share - Valkyrie HIVE XP (Target)": "GainExperienc_experience_id_1188",
  "Vehicle Gunner Kill Assist Share - Valkyrie HIVE XP (Target)": "GainExperienc_experience_id_1189",
  "Vehicle Passenger Kill Share - Valkyrie HIVE XP (Target)": "GainExperienc_experience_id_1190",
  "Vehicle Driver Kill Assist Share - Valkyrie HIVE XP (Target)": "GainExperienc_experience_id_1191",
  "Flash Kill by Valkyrie Gunner HIVE XP (Target)": "GainExperienc_experience_id_1192",
  "Sunderer Kill by Valkyrie Gunner HIVE XP (Target)": "GainExperienc_experience_id_1193",
  "Lightning Kill by Valkyrie Gunne HIVE XP (Target)": "GainExperienc_experience_id_1194",
  "Vanguard Kill by Valkyrie Gunner HIVE XP (Target)": "GainExperienc_experience_id_1195",
  "Prowler Kill by Valkyrie Gunner HIVE XP (Target)": "GainExperienc_experience_id_1196",
  "Reaver Kill by Valkyrie Gunner HIVE XP (Source)": "GainExperienc_experience_id_1197",
  "Mosquito Kill by Valkyrie Gunner HIVE XP (Source)": "GainExperienc_experience_id_1198",
  "Lib Kill by Valkyrie HIVE XP (Source)": "GainExperienc_experience_id_1199",
  "Galaxy Kill by Valkyrie Gunner HIVE XP (Source)": "GainExperienc_experience_id_1200",
  "Magrider Kill by Valkyrie Gunner HIVE XP (Source)": "GainExperienc_experience_id_1201",
  "Scythe Kill by Valkyrie Gunner HIVE XP (Source)": "GainExperienc_experience_id_1202",
  "Snowman Kill by Valkyrie Gunner HIVE XP (Source)": "GainExperienc_experience_id_1203",
  "Valkyrie Kill by Valkyrie Gunner HIVE XP (Source)": "GainExperienc_experience_id_1204",
  "Harasser Kill by Valkyrie Gunner HIVE XP (Source)": "GainExperienc_experience_id_1205",
  "Valkyrie Kill by Harasser Gunner HIVE XP (Source)": "GainExperienc_experience_id_1206",
  "Destroy Spitfire Turret HIVE XP (Source)": "GainExperienc_experience_id_1207",
  "Vehicle Gunner Kill Share - Spitfire HIVE XP (Source)": "GainExperienc_experience_id_1208",
  "Vehicle Gunner Kill Assist Share - Spitfire HIVE XP (Source)": "GainExperienc_experience_id_1209",
  "Vehicle Passenger Kill Share - Spitfire HIVE XP (Source)": "GainExperienc_experience_id_1210",
  "Vehicle Driver Kill Assist Share - Engi Turret HIVE XP (Source)": "GainExperienc_experience_id_1211",
  "Kill/Destroy - Construction - Med HIVE XP (Source)": "GainExperienc_experience_id_1212",
  "Repair - Construction - Med HIVE XP (Source)": "GainExperienc_experience_id_1214",
  "KillAssist - Construction - Med HIVE XP (Source)": "GainExperienc_experience_id_1215",
  "Reaver Kill by Valkyrie Gunner HIVE XP (Target)": "GainExperienc_experience_id_1217",
  "Mosquito Kill by Valkyrie Gunner HIVE XP (Target)": "GainExperienc_experience_id_1218",
  "Lib Kill by Valkyrie HIVE XP (Target)": "GainExperienc_experience_id_1219",
  "Galaxy Kill by Valkyrie Gunner HIVE XP (Target)": "GainExperienc_experience_id_1220",
  "Magrider Kill by Valkyrie Gunner HIVE XP (Target)": "GainExperienc_experience_id_1221",
  "Scythe Kill by Valkyrie Gunner HIVE XP (Target)": "GainExperienc_experience_id_1222",
  "Snowman Kill by Valkyrie Gunner HIVE XP (Target)": "GainExperienc_experience_id_1223",
  "Valkyrie Kill by Valkyrie Gunner HIVE XP (Target)": "GainExperienc_experience_id_1224",
  "Harasser Kill by Valkyrie Gunner HIVE XP (Target)": "GainExperienc_experience_id_1225",
  "Valkyrie Kill by Harasser Gunner HIVE XP (Target)": "GainExperienc_experience_id_1226",
  "Destroy Spitfire Turret HIVE XP (Target)": "GainExperienc_experience_id_1227",
  "Vehicle Gunner Kill Share - Spitfire HIVE XP (Target)": "GainExperienc_experience_id_1228",
  "Vehicle Gunner Kill Assist Share - Spitfire HIVE XP (Target)": "GainExperienc_experience_id_1229",
  "Vehicle Passenger Kill Share - Spitfire HIVE XP (Target)": "GainExperienc_experience_id_1230",
  "Vehicle Driver Kill Assist Share - Engi Turret HIVE XP (Target)": "GainExperienc_experience_id_1231",
  "Kill/Destroy - Construction - Med HIVE XP (Target)": "GainExperienc_experience_id_1232",
  "Repair - Construction - Med HIVE XP (Target)": "GainExperienc_experience_id_1234",
  "KillAssist - Construction - Med HIVE XP (Target)": "GainExperienc_experience_id_1235",
  "Spot Kill - Construction - Med  HIVE XP (Source)": "GainExperienc_experience_id_1237",
  "Gunner Kill Share - Construction - Med HIVE XP (Source)": "GainExperienc_experience_id_1238",
  "Gunner Kill Assist Share - Construction - Med HIVE XP (Source)": "GainExperienc_experience_id_1239",
  "Vehicle Passenger Kill Share - Construction - Med HIVE XP (Source)": "GainExperienc_experience_id_1240",
  "Driver Kill Aassist Share - Construction - Med HIVE XP (Source)": "GainExperienc_experience_id_1241",
  "Vehicle Ram Kill - Construction - Small HIVE XP (Source)": "GainExperienc_experience_id_1242",
  "Kill/Destroy - Construction - Small HIVE XP (Source)": "GainExperienc_experience_id_1243",
  "Repair - Construction - Small HIVE XP (Source)": "GainExperienc_experience_id_1245",
  "KillAssist - Construction - Small HIVE XP (Source)": "GainExperienc_experience_id_1246",
  "Spot Kill - Construction - Small  HIVE XP (Source)": "GainExperienc_experience_id_1248",
  "Gunner Kill Share - Construction - Small HIVE XP (Source)": "GainExperienc_experience_id_1249",
  "Gunner Kill Assist Share - Construction - Small HIVE XP (Source)": "GainExperienc_experience_id_1250",
  "Vehicle Passenger Kill Share - Construction - Small HIVE XP (Source)": "GainExperienc_experience_id_1251",
  "Driver Kill Aassist Share - Construction - Small HIVE XP (Source)": "GainExperienc_experience_id_1252",
  "Vehicle Ram Kill - Construction - Large HIVE XP (Source)": "GainExperienc_experience_id_1253",
  "Kill/Destroy - Construction - Large HIVE XP (Source)": "GainExperienc_experience_id_1254",
  "Spot Kill - Construction - Med  HIVE XP (Target)": "GainExperienc_experience_id_1255",
  "Gunner Kill Share - Construction - Med HIVE XP (Target)": "GainExperienc_experience_id_1256",
  "Gunner Kill Assist Share - Construction - Med HIVE XP (Target)": "GainExperienc_experience_id_1257",
  "Vehicle Passenger Kill Share - Construction - Med HIVE XP (Target)": "GainExperienc_experience_id_1258",
  "Driver Kill Aassist Share - Construction - Med HIVE XP (Target)": "GainExperienc_experience_id_1259",
  "Vehicle Ram Kill - Construction - Small HIVE XP (Target)": "GainExperienc_experience_id_1260",
  "Kill/Destroy - Construction - Small HIVE XP (Target)": "GainExperienc_experience_id_1261",
  "Repair - Construction - Small HIVE XP (Target)": "GainExperienc_experience_id_1263",
  "KillAssist - Construction - Small HIVE XP (Target)": "GainExperienc_experience_id_1264",
  "Spot Kill - Construction - Small  HIVE XP (Target)": "GainExperienc_experience_id_1266",
  "Gunner Kill Share - Construction - Small HIVE XP (Target)": "GainExperienc_experience_id_1267",
  "Gunner Kill Assist Share - Construction - Small HIVE XP (Target)": "GainExperienc_experience_id_1268",
  "Vehicle Passenger Kill Share - Construction - Small HIVE XP (Target)": "GainExperienc_experience_id_1269",
  "Driver Kill Aassist Share - Construction - Small HIVE XP (Target)": "GainExperienc_experience_id_1270",
  "Vehicle Ram Kill - Construction - Large HIVE XP (Target)": "GainExperienc_experience_id_1271",
  "Kill/Destroy - Construction - Large HIVE XP (Target)": "GainExperienc_experience_id_1272",
  "Repair - Construction - Large HIVE XP (Source)": "GainExperienc_experience_id_1273",
  "KillAssist - Construction - Large HIVE XP (Source)": "GainExperienc_experience_id_1274",
  "Spot Kill - Construction - Large  HIVE XP (Source)": "GainExperienc_experience_id_1276",
  "Gunner Kill Share - Construction - Large HIVE XP (Source)": "GainExperienc_experience_id_1277",
  "Gunner Kill Assist Share - Construction - Large HIVE XP (Source)": "GainExperienc_experience_id_1278",
  "Vehicle Passenger Kill Share - Construction - Large HIVE XP (Source)": "GainExperienc_experience_id_1279",
  "Driver Kill Aassist Share - Construction - Large HIVE XP (Source)": "GainExperienc_experience_id_1280",
  "Vehicle Ram Kill - Construction - Core HIVE XP (Source)": "GainExperienc_experience_id_1281",
  "Kill/Destroy - Construction - Core HIVE XP (Source)": "GainExperienc_experience_id_1282",
  "Repair - Construction - Core HIVE XP (Source)": "GainExperienc_experience_id_1283",
  "KillAssist - Construction - Core HIVE XP (Source)": "GainExperienc_experience_id_1284",
  "Spot Kill - Construction - Core  HIVE XP (Source)": "GainExperienc_experience_id_1286",
  "Gunner Kill Share - Construction - Core HIVE XP (Source)": "GainExperienc_experience_id_1287",
  "Gunner Kill Assist Share - Construction - Core HIVE XP (Source)": "GainExperienc_experience_id_1288",
  "Repair - Construction - Large HIVE XP (Target)": "GainExperienc_experience_id_1289",
  "KillAssist - Construction - Large HIVE XP (Target)": "GainExperienc_experience_id_1290",
  "Spot Kill - Construction - Large  HIVE XP (Target)": "GainExperienc_experience_id_1292"
}