/*
  list of the partecipants of the ops from discord (for now)
  API for PS2 and discord from .env

  https://discordjs.guide/preparations/setting-up-a-bot-application.html#creating-your-bot

  https://discord.com/developers/applications/794697883596881940/information

  http://census.daybreakgames.com/get/ps2:v2/characters_event/?character_id=5428016459730317697,5428117870052769409&c:limit=100&type=KILL,DEATH
  http://census.daybreakgames.com/s:example/json/get/ps2:v2/character/5428016459730317697
  http://census.daybreakgames.com/get/ps2:v2/character/?name.first_lower=pholanx


  My obj(dict) will be
  players = {
    <id>:{"name":<name>, "heals":<heals>, etc }
  }
*/
const dotenv = require('dotenv');
const WebSocket = require('ws');
const got = require('got');


// TODO: get names from discord
// TODO: clean the names from @ or [BJAY]
// TODO: get lowercase
// const list_of_names = ["fofila", "vaaragh"]
const list_of_names = ["fofila"]
const dict_of_values = {}

require('dotenv').config();

main();


/*
given the name of the player, the info(params) needed and the dictionary you want to populate
call the PS2 API and add the response to the dict
*/
async function setIDfromName(name=null, params="&c:show=character_id", dict=dict_of_values){
  // TODO: if name is empty crash
  try {
    var response = await got(`http://census.daybreakgames.com/get/ps2:v2/character/?name.first_lower=${name}${params}`);
    console.log(JSON.parse(response.body).character_list[0].character_id)
    dict_of_values[JSON.parse(response.body).character_list[0].character_id] = {}
    dict_of_values[JSON.parse(response.body).character_list[0].character_id]["name"] = name;
    console.log(dict_of_values);
  } catch (error) {
    console.log(error);
  }
}

/*
function that creates the connection to the WS
*/
async function createWSConnection(url_to_ws){
  const connection = new WebSocket(url_to_ws)
  connection.onerror = error => {console.error(`WebSocket error: ${error}`)}
  return connection;
}

/*
from a list of names get the ID and populate
*/
async function populate_names(names){
  for (let i = 0; i < names.length; i++) {
    setIDfromName(names[i]);  
  }
}

/*
the first function (needed for the async hell)
*/
async function main(){
  let list_of_ids = []
  await populate_names(list_of_names);
  for (const id in dict_of_values) {
    list_of_ids.push(id)
  }
  console.log(dict_of_values);
  const ws = await createWSConnection(`wss://push.planetside2.com/streaming?environment=ps2&service-id=s:${process.env.PS2_TOKEN}`);
  ws.onopen = () => {
    /*
    add here all the request to the ws
    */
    console.info('Connection to PS2 server open!')
    ws.send('{"action":"clearSubscribe","all":"true","service":"event"}')
    let message = `{"service":"event","action":"subscribe","characters":[${list_of_ids}],"eventNames":["GainExperience_experience_id_4","GainExperience_experience_id_5","GainExperience_experience_id_7"]}`;
    console.log(message);
    // TODO: unsubscribe to heartbeat
    ws.send(message)
  }
  /*
    navigate di e.data to get the value needed
    TODO: add a list as a log of events
  */
  ws.onmessage = (e) => {
    let message_dict = JSON.parse(e.data);
    if(message_dict.type !== "heartbeat"){
      // it is a useful message
      console.log(e.data.payload)

    }
    // {"payload":{"amount":"75","character_id":"5428016459730317697","event_name":"GainExperience","experience_id":"7","loadout_id":"4","other_id":"5428716652642740209","timestamp":"1609584372","world_id":"13","zone_id":"4"},"service":"event","type":"serviceMessage"}
    // {"online":{"EventServerEndpoint_Cobalt_13":"true","EventServerEndpoint_Connery_1":"true","EventServerEndpoint_Emerald_17":"true","EventServerEndpoint_Jaeger_19":"true","EventServerEndpoint_Miller_10":"true","EventServerEndpoint_Soltech_40":"true"},"service":"event","type":"heartbeat"}
  }
}



// for future use
const type_gain_experience = {
  "GainExperienc_experience_id_1":"Kill Player",
  "GainExperienc_experience_id_2":"Kill Player Assist",
  "GainExperienc_experience_id_3":"Kill Player Spawn Assist",
  "GainExperienc_experience_id_4":"Heal Player",
  "GainExperienc_experience_id_5":"Heal Assist",
  "GainExperienc_experience_id_6":"MAX Repair",
  "GainExperienc_experience_id_7":"Revive",
  "GainExperienc_experience_id_8":"Kill Streak",
  "GainExperienc_experience_id_10":"Domination Kill",
  "GainExperienc_experience_id_11":"Revenge Kill",
  "GainExperienc_experience_id_15":"Control Point - Defend",
  "GainExperienc_experience_id_16":"Control Point - Attack",
  "GainExperienc_experience_id_19":"Facility Captured (Not Used)",
  "GainExperienc_experience_id_21":"Destroy Secondary Objective",
  "GainExperienc_experience_id_22":"Destroy SecondaryObjectiveAssist",
  "GainExperienc_experience_id_24":"Vehicle Destruction - Flash",
  "GainExperienc_experience_id_25":"Multiple Kill",
  "GainExperienc_experience_id_26":"Vehicle RoadKill",
  "GainExperienc_experience_id_28":"Squad Repair - Flash",
  "GainExperienc_experience_id_29":"Kill Player Class MAX",
  "GainExperienc_experience_id_30":"Transport Assist",
  "GainExperienc_experience_id_31":"Vehicle Repair - Flash",
  "GainExperienc_experience_id_32":"Nemesis Kill",
  "GainExperienc_experience_id_34":"Resupply Player",
  "GainExperienc_experience_id_36":"Spot Kill",
  "GainExperienc_experience_id_37":"Headshot",
  "GainExperienc_experience_id_38":"Stop Kill Streak",
  "GainExperienc_experience_id_47":"Meta Game Event reward",
  "GainExperienc_experience_id_51":"Squad Heal",
  "GainExperienc_experience_id_53":"Squad Revive",
  "GainExperienc_experience_id_54":"Squad Spot Kill",
  "GainExperienc_experience_id_55":"Squad Resupply",
  "GainExperienc_experience_id_56":"Squad Spawn",
  "GainExperienc_experience_id_57":"Destroy Engineer Turret",
  "GainExperienc_experience_id_58":"Vehicle Destruction - Phalanx",
  "GainExperienc_experience_id_59":"Vehicle Destruction - Drop Pod",
  "GainExperienc_experience_id_60":"Vehicle Destruction - Galaxy",
  "GainExperienc_experience_id_61":"Vehicle Destruction - Liberator",
  "GainExperienc_experience_id_62":"Vehicle Destruction - Lightning",
  "GainExperienc_experience_id_63":"Vehicle Destruction - Magrider",
  "GainExperienc_experience_id_64":"Vehicle Destruction - Mosquito",
  "GainExperienc_experience_id_65":"Vehicle Destruction - Prowler",
  "GainExperienc_experience_id_66":"Vehicle Destruction - Reaver",
  "GainExperienc_experience_id_67":"Vehicle Destruction - Scythe",
  "GainExperienc_experience_id_68":"Vehicle Destruction - Sunderer",
  "GainExperienc_experience_id_69":"Vehicle Destruction - Vanguard",
  "GainExperienc_experience_id_72":"Vehicle Ram Bonus",
  "GainExperienc_experience_id_73":"Vehicle Ram Kill - Engi Turret",
  "GainExperienc_experience_id_74":"Vehicle Ram Kill - Phalanx",
  "GainExperienc_experience_id_75":"Vehicle Ram Kill - Drop Pod",
  "GainExperienc_experience_id_76":"Vehicle Ram Kill - Galaxy",
  "GainExperienc_experience_id_77":"Vehicle Ram Kill - Liberator",
  "GainExperienc_experience_id_78":"Vehicle Ram Kill - Lightning",
  "GainExperienc_experience_id_79":"Vehicle Ram Kill - Magrider",
  "GainExperienc_experience_id_80":"Vehicle Ram Kill - Mosquito",
  "GainExperienc_experience_id_81":"Vehicle Ram Kill - Prowler",
  "GainExperienc_experience_id_82":"Vehicle Ram Kill - Reaver",
  "GainExperienc_experience_id_83":"Vehicle Ram Kill - Scythe",
  "GainExperienc_experience_id_84":"Vehicle Ram Kill - Sunderer",
  "GainExperienc_experience_id_85":"Vehicle Ram Kill - Vanguard",
  "GainExperienc_experience_id_86":"Explosive Destruction",
  "GainExperienc_experience_id_87":"Secondary Facility Object Repair",
  "GainExperienc_experience_id_88":"Vehicle Repair - Engi Turret",
  "GainExperienc_experience_id_89":"Vehicle Repair - Phalanx",
  "GainExperienc_experience_id_90":"Vehicle Repair - Drop Pod",
  "GainExperienc_experience_id_91":"Vehicle Repair - Galaxy",
  "GainExperienc_experience_id_92":"Vehicle Repair - Liberator",
  "GainExperienc_experience_id_93":"Vehicle Repair - Lightning",
  "GainExperienc_experience_id_94":"Vehicle Repair - Magrider",
  "GainExperienc_experience_id_95":"Vehicle Repair - Mosquito",
  "GainExperienc_experience_id_96":"Vehicle Repair - Prowler",
  "GainExperienc_experience_id_97":"Vehicle Repair - Reaver",
  "GainExperienc_experience_id_98":"Vehicle Repair - Scythe",
  "GainExperienc_experience_id_99":"Vehicle Repair - Sunderer",
  "GainExperienc_experience_id_100":"Vehicle Repair - Vanguard",
  "GainExperienc_experience_id_101":"Kill Assist - Flash",
  "GainExperienc_experience_id_102":"Kill Assist - Engi Turret",
  "GainExperienc_experience_id_103":"Kill Assist - Phalanx",
  "GainExperienc_experience_id_104":"Kill Assist - Drop Pod",
  "GainExperienc_experience_id_105":"Kill Assist - Galaxy",
  "GainExperienc_experience_id_106":"Kill Assist - Liberator",
  "GainExperienc_experience_id_107":"Kill Assist - Lightning",
  "GainExperienc_experience_id_108":"Kill Assist - Magrider",
  "GainExperienc_experience_id_109":"Kill Assist - Mosquito",
  "GainExperienc_experience_id_110":"Kill Assist - Prowler",
  "GainExperienc_experience_id_111":"Kill Assist - Reaver",
  "GainExperienc_experience_id_112":"Kill Assist - Scythe",
  "GainExperienc_experience_id_113":"Kill Assist - Sunderer",
  "GainExperienc_experience_id_114":"Kill Assist - Vanguard",
  "GainExperienc_experience_id_129":"Squad Repair - Engi Turret",
  "GainExperienc_experience_id_130":"Squad Repair - Phalanx",
  "GainExperienc_experience_id_131":"Squad Repair - Drop Pod",
  "GainExperienc_experience_id_132":"Squad Repair - Galaxy",
  "GainExperienc_experience_id_133":"Squad Repair - Liberator",
  "GainExperienc_experience_id_134":"Squad Repair - Lightning",
  "GainExperienc_experience_id_135":"Squad Repair - Magrider",
  "GainExperienc_experience_id_136":"Squad Repair - Mosquito",
  "GainExperienc_experience_id_137":"Squad Repair - Prowler",
  "GainExperienc_experience_id_138":"Squad Repair - Reaver",
  "GainExperienc_experience_id_139":"Squad Repair - Scythe",
  "GainExperienc_experience_id_140":"Squad Repair - Sunderer",
  "GainExperienc_experience_id_141":"Squad Repair - Vanguard",
  "GainExperienc_experience_id_142":"Squad MAX Repair",
  "GainExperienc_experience_id_143":"Drop Pod Kill",
  "GainExperienc_experience_id_146":"Player Kill by Sunderer Gunner",
  "GainExperienc_experience_id_148":"Player Kill by Magrider Gunner",
  "GainExperienc_experience_id_149":"Player Kill by Vanguard Gunner",
  "GainExperienc_experience_id_150":"Player Kill by Prowler Gunner",
  "GainExperienc_experience_id_154":"Player Kill by Liberator Gunner",
  "GainExperienc_experience_id_155":"Player Kill by Galaxy Gunner",
  "GainExperienc_experience_id_159":"Flash Kill by Sunderer Gunner",
  "GainExperienc_experience_id_160":"Sunderer Kill by Sunderer Gunner",
  "GainExperienc_experience_id_161":"Lightning Kill by Sunderer Gunne",
  "GainExperienc_experience_id_162":"Magrider Kill by Sunderer Gunner",
  "GainExperienc_experience_id_163":"Vanguard Kill by Sunderer Gunner",
  "GainExperienc_experience_id_164":"Prowler Kill by Sunderer Gunner",
  "GainExperienc_experience_id_165":"Scythe Kill by Sunderer Gunner",
  "GainExperienc_experience_id_166":"Reaver Kill by Sunderer Gunner",
  "GainExperienc_experience_id_167":"Mosquito Kill by Sunderer Gunner",
  "GainExperienc_experience_id_168":"Lib Kill by Sunderer",
  "GainExperienc_experience_id_169":"Galaxy Kill by Sunderer Gunner",
  "GainExperienc_experience_id_181":"Flash Kill by Magrider Gunner",
  "GainExperienc_experience_id_182":"Sunderer Kill by Magrider Gunner",
  "GainExperienc_experience_id_183":"Lightning Kill by Magrider Gunne",
  "GainExperienc_experience_id_184":"Vanguard Kill by Magrider Gunner",
  "GainExperienc_experience_id_185":"Prowler Kill by Magrider Gunner",
  "GainExperienc_experience_id_186":"Reaver Kill by Magrider Gunner",
  "GainExperienc_experience_id_187":"Mosquito Kill by Magrider Gunner",
  "GainExperienc_experience_id_188":"Lib Kill by Magrider",
  "GainExperienc_experience_id_189":"Galaxy Kill by Magrider Gunner",
  "GainExperienc_experience_id_190":"Flash Kill by Vanguard Gunner",
  "GainExperienc_experience_id_191":"Sunderer Kill by Vanguard Gunner",
  "GainExperienc_experience_id_192":"Lightning Kill by Vanguard Gunne",
  "GainExperienc_experience_id_193":"Magrider Kill by Vanguard Gunner",
  "GainExperienc_experience_id_195":"Prowler Kill by Vanguard Gunner",
  "GainExperienc_experience_id_196":"Scythe Kill by Vanguard Gunner",
  "GainExperienc_experience_id_197":"Mosquito Kill by Vanguard Gunner",
  "GainExperienc_experience_id_198":"Lib Kill by Vanguard",
  "GainExperienc_experience_id_199":"Galaxy Kill by Vanguard Gunner",
  "GainExperienc_experience_id_200":"Flash Kill by Prowler Gunner",
  "GainExperienc_experience_id_201":"Galaxy Spawn Bonus",
  "GainExperienc_experience_id_202":"Sunderer Kill by Prowler Gunner",
  "GainExperienc_experience_id_203":"Lightning Kill by Prowler Gunner",
  "GainExperienc_experience_id_204":"Magrider Kill by Prowler Gunner",
  "GainExperienc_experience_id_205":"Vanguard Kill by Prowler Gunner",
  "GainExperienc_experience_id_207":"Scythe Kill by Prowler Gunner",
  "GainExperienc_experience_id_208":"Reaver Kill by Prowler Gunner",
  "GainExperienc_experience_id_209":"Liberator Kill by Prowler Gunner",
  "GainExperienc_experience_id_210":"Galaxy Kill by Prowler Gunner",
  "GainExperienc_experience_id_211":"Flash Kill by Liberator Gunner",
  "GainExperienc_experience_id_212":"Sunderer Kill by Lib Gunner",
  "GainExperienc_experience_id_213":"Lightning Kill by Liberator Gunn",
  "GainExperienc_experience_id_214":"Magrider Kill by Lib Gunner",
  "GainExperienc_experience_id_215":"Vanguard Kill by Lib Gunner",
  "GainExperienc_experience_id_216":"Prowler Kill by Liberator Gunner",
  "GainExperienc_experience_id_217":"Scythe Kill by Liberator Gunner",
  "GainExperienc_experience_id_218":"Reaver Kill by Liberator Gunner",
  "GainExperienc_experience_id_219":"Mosquito Kill by Lib Gunner",
  "GainExperienc_experience_id_220":"Lib Kill by Liberator",
  "GainExperienc_experience_id_221":"Galaxy Kill by Liberator Gunner",
  "GainExperienc_experience_id_222":"Flash Kill by Galaxy Gunner",
  "GainExperienc_experience_id_223":"Sunderer Kill by Galaxy Gunner",
  "GainExperienc_experience_id_224":"Lightning Kill by Galaxy Gunner",
  "GainExperienc_experience_id_225":"Magrider Kill by Galaxy Gunner",
  "GainExperienc_experience_id_226":"Vanguard Kill by Galaxy Gunner",
  "GainExperienc_experience_id_227":"Prowler Kill by Galaxy Gunner",
  "GainExperienc_experience_id_228":"Scythe Kill by Galaxy Gunner",
  "GainExperienc_experience_id_229":"Reaver Kill by Galaxy Gunner",
  "GainExperienc_experience_id_230":"Mosquito Kill by Galaxy Gunner",
  "GainExperienc_experience_id_231":"LibKill by Galaxy Gunner",
  "GainExperienc_experience_id_232":"Galaxy Kill by Galaxy Gunner",
  "GainExperienc_experience_id_233":"Sunderer Spawn Bonus",
  "GainExperienc_experience_id_234":"Facility placed bomb",
  "GainExperienc_experience_id_235":"Facility defused bomb",
  "GainExperienc_experience_id_236":"Facility Terminal Hack",
  "GainExperienc_experience_id_237":"Facility Turret Hack",
  "GainExperienc_experience_id_240":"Vehicle Resupply",
  "GainExperienc_experience_id_241":"Squad Vehicle Resupply",
  "GainExperienc_experience_id_242":"Spot Kill - Flash",
  "GainExperienc_experience_id_243":"Spot Kill - Engi Turret",
  "GainExperienc_experience_id_244":"Spot Kill - Phalanx",
  "GainExperienc_experience_id_245":"Spot Kill - Drop Pod",
  "GainExperienc_experience_id_246":"Spot Kill - Galaxy",
  "GainExperienc_experience_id_247":"Spot Kill - Liberator",
  "GainExperienc_experience_id_248":"Spot Kill - Lightning",
  "GainExperienc_experience_id_249":"Spot Kill - Magrider",
  "GainExperienc_experience_id_250":"Spot Kill - Mosquito",
  "GainExperienc_experience_id_251":"Spot Kill - Prowler",
  "GainExperienc_experience_id_252":"Spot Kill - Reaver",
  "GainExperienc_experience_id_253":"Spot Kill - Scythe",
  "GainExperienc_experience_id_254":"Spot Kill - Sunderer",
  "GainExperienc_experience_id_255":"Spot Kill - Vanguard",
  "GainExperienc_experience_id_256":"Squad Spot Kill - Flash",
  "GainExperienc_experience_id_257":"Squad Spot Kill - Engi Turret",
  "GainExperienc_experience_id_258":"Squad Spot Kill - Phalanx",
  "GainExperienc_experience_id_259":"Squad Spot Kill - Drop Pod",
  "GainExperienc_experience_id_260":"Squad Spot Kill - Galaxy",
  "GainExperienc_experience_id_261":"Squad Spot Kill - Liberator",
  "GainExperienc_experience_id_262":"Squad Spot Kill - Lightning",
  "GainExperienc_experience_id_263":"Squad Spot Kill - Magrider",
  "GainExperienc_experience_id_264":"Squad Spot Kill - Mosquito",
  "GainExperienc_experience_id_265":"Squad Spot Kill - Prowler",
  "GainExperienc_experience_id_266":"Squad Spot Kill - Reaver",
  "GainExperienc_experience_id_267":"Squad Spot Kill - Scythe",
  "GainExperienc_experience_id_268":"Squad Spot Kill - Sunderer",
  "GainExperienc_experience_id_269":"Squad Spot Kill - Vanguard",
  "GainExperienc_experience_id_270":"Squad Spawn Beacon Kill",
  "GainExperienc_experience_id_272":"Convert Capture Point",
  "GainExperienc_experience_id_275":"Terminal Kill",
  "GainExperienc_experience_id_276":"Terminal Repair",
  "GainExperienc_experience_id_277":"Spawn Kill",
  "GainExperienc_experience_id_278":"Priority Kill",
  "GainExperienc_experience_id_279":"High Priority Kill",
  "GainExperienc_experience_id_280":"Lighting Damage (Infantry vs Vehicle)",
  "GainExperienc_experience_id_281":"Prowler Damage (Infantry vs Vehicle)",
  "GainExperienc_experience_id_283":"Galaxy Damage",
  "GainExperienc_experience_id_284":"Liberator Damage",
  "GainExperienc_experience_id_285":"Magrider Damage (Infantry vs Vehicle)",
  "GainExperienc_experience_id_286":"Mosquito Damage",
  "GainExperienc_experience_id_287":"Reaver Damage",
  "GainExperienc_experience_id_288":"Scythe Damage",
  "GainExperienc_experience_id_289":"Sunderer Damage (Infantry vs Vehicle)",
  "GainExperienc_experience_id_290":"Vanguard Damage (Infantry vs Vehicle)",
  "GainExperienc_experience_id_291":"Ribbon Experience",
  "GainExperienc_experience_id_293":"Motion Detect",
  "GainExperienc_experience_id_294":"Squad Motion Spot",
  "GainExperienc_experience_id_300":"Vehicle Ram Kill - Harasser",
  "GainExperienc_experience_id_301":"Vehicle Destruction - Harasser",
  "GainExperienc_experience_id_302":"Squad Repair - Harasser",
  "GainExperienc_experience_id_303":"Vehicle Repair - Harasser",
  "GainExperienc_experience_id_304":"Kill Assist - Harasser",
  "GainExperienc_experience_id_306":"Spot Kill - Harasser",
  "GainExperienc_experience_id_307":"Squad Spot Kill - Harasser",
  "GainExperienc_experience_id_308":"Harasser Kill by Sunderer Gunne",
  "GainExperienc_experience_id_309":"Harasser Kill by Magrider Gunne",
  "GainExperienc_experience_id_310":"Harasser Kill by Vanguard Gunne",
  "GainExperienc_experience_id_311":"Harasser Kill by Prowler Gunner",
  "GainExperienc_experience_id_312":"Harasser Kill by Liberator Gunn",
  "GainExperienc_experience_id_313":"Harasser Kill by Galaxy Gunner",
  "GainExperienc_experience_id_314":"Player Kill by Harasser Gunner",
  "GainExperienc_experience_id_315":"Flash Kill by Harasser Gunner",
  "GainExperienc_experience_id_316":"Sunderer Kill by Harasser Gunner",
  "GainExperienc_experience_id_317":"Lightning Kill by Harasser Gunne",
  "GainExperienc_experience_id_318":"Vanguard Kill by Harasser Gunner",
  "GainExperienc_experience_id_319":"Prowler Kill by Harasser Gunner",
  "GainExperienc_experience_id_320":"Reaver Kill by Harasser Gunner",
  "GainExperienc_experience_id_321":"Mosquito Kill by Harasser Gunner",
  "GainExperienc_experience_id_322":"Lib Kill by Harasser",
  "GainExperienc_experience_id_323":"Galaxy Kill by Harasser Gunner",
  "GainExperienc_experience_id_324":"Harasser Kill by Harasser Gunner",
  "GainExperienc_experience_id_325":"Magrider Kill by Harasser Gunner",
  "GainExperienc_experience_id_326":"Scythe Kill by Harasser Gunner",
  "GainExperienc_experience_id_327":"Tank Mine Despawn/Defusal",
  "GainExperienc_experience_id_328":"Alert Reward",
  "GainExperienc_experience_id_322":"Tank Hunter Bonus - Prowler Kill",
  "GainExperienc_experience_id_330":"Tank Hunter Bonus - Magrider Kil",
  "GainExperienc_experience_id_331":"Dogfighter Bonus - Mosquito Kill",
  "GainExperienc_experience_id_332":"Dogfighter Bonus - Reaver Kill",
  "GainExperienc_experience_id_333":"Dogfighter Bonus - Scythe Kill",
  "GainExperienc_experience_id_334":"Tank Hunter Bonus - Vanguard Kil",
  "GainExperienc_experience_id_335":"Savior Kill (Non MAX)",
  "GainExperienc_experience_id_336":"Saved",
  "GainExperienc_experience_id_337":"Holiday Event NPC: Kill",
  "GainExperienc_experience_id_338":"Holiday Event NPC Gold: Kill",
  "GainExperienc_experience_id_339":"Snowman Kill by Sunderer Gunner",
  "GainExperienc_experience_id_340":"Snowman Kill by Magrider Gunner",
  "GainExperienc_experience_id_341":"Snowman Kill by Vanguard Gunner",
  "GainExperienc_experience_id_342":"Snowman Kill by Prowler Gunner",
  "GainExperienc_experience_id_343":"Snowman Kill by Liberator Gunner",
  "GainExperienc_experience_id_344":"Snowman Kill by Galaxy Gunner",
  "GainExperienc_experience_id_345":"Snowman Kill by Harasser Gunner",
  "GainExperienc_experience_id_346":"GSnowman Kill by Sunder Gunner",
  "GainExperienc_experience_id_347":"GSnowman Kill by Mag Gunner",
  "GainExperienc_experience_id_348":"GSnowman Kill by Vang Gunner",
  "GainExperienc_experience_id_349":"GSnowman Kill by Prow Gunner",
  "GainExperienc_experience_id_350":"GSnowman Kill by Lib Gunner",
  "GainExperienc_experience_id_351":"GSnowman Kill by Gal Gunner",
  "GainExperienc_experience_id_352":"GSnowman Kill by Haras Gunner",
  "GainExperienc_experience_id_353":"Scout Radar Detect",
  "GainExperienc_experience_id_354":"Squad Scout Radar Detect",
  "GainExperienc_experience_id_355":"Squad Vehicle Spawn Bonus",
  "GainExperienc_experience_id_356":"Vehicle Ram Kill - R Drone",
  "GainExperienc_experience_id_357":"Vehicle Destruction - R Drone",
  "GainExperienc_experience_id_358":"Squad Repair - R Drone",
  "GainExperienc_experience_id_359":"Vehicle Repair - R Drone",
  "GainExperienc_experience_id_360":"Kill Assist - R Drone",
  "GainExperienc_experience_id_362":"R Drone Kill by Harasser Gunner",
  "GainExperienc_experience_id_363":"R Drone Kill by Sunderer Gunner",
  "GainExperienc_experience_id_364":"R Drone Kill by Magrider Gunner",
  "GainExperienc_experience_id_365":"R Drone Kill by Prowler Gunner",
  "GainExperienc_experience_id_366":"R Drone Kill by Lib Gunner",
  "GainExperienc_experience_id_367":"R Drone Kill by Galaxy Gunner",
  "GainExperienc_experience_id_368":"Spot Kill - R Drone",
  "GainExperienc_experience_id_369":"Squad Spot Kill - R Drone",
  "GainExperienc_experience_id_370":"Motion Sensor Spotter Kill",
  "GainExperienc_experience_id_371":"Kill Player Priority Assist",
  "GainExperienc_experience_id_372":"Kill Player High Priority Assist",
  "GainExperienc_experience_id_437":"Shield Regen Tool Kill",
  "GainExperienc_experience_id_438":"Shield Repair",
  "GainExperienc_experience_id_439":"Squad Shield Repair",
  "GainExperienc_experience_id_440":"Chain Expl Assist: Infantry",
  "GainExperienc_experience_id_441":"Chain Expl Assist: Flash",
  "GainExperienc_experience_id_501":"Vehicle Destruction - Valkyrie",
  "GainExperienc_experience_id_502":"Vehicle Ram Kill - Valkyrie",
  "GainExperienc_experience_id_503":"Vehicle Repair - Valkyrie",
  "GainExperienc_experience_id_504":"Kill Assist - Valkyrie",
  "GainExperienc_experience_id_505":"Squad Repair - Valkyrie",
  "GainExperienc_experience_id_506":"Spot Kill - Valkyrie",
  "GainExperienc_experience_id_507":"Squad Spot Kill - Valkyrie",
  "GainExperienc_experience_id_508":"Valkyrie Damage",
  "GainExperienc_experience_id_509":"Valkyrie Kill by Sunderer Gunner",
  "GainExperienc_experience_id_510":"Valkyrie Kill by Magrider Gunner",
  "GainExperienc_experience_id_511":"Valkyrie Kill by Vanguard Gunner",
  "GainExperienc_experience_id_512":"Valkyrie Kill by Prowler Gunner",
  "GainExperienc_experience_id_513":"Valkyrie Kill by Liberator Gunner",
  "GainExperienc_experience_id_514":"Valkyrie Kill by Galaxy Gunner",
  "GainExperienc_experience_id_515":"Player Kill by Valkyrie Gunner",
  "GainExperienc_experience_id_520":"Flash Kill by Valkyrie Gunner",
  "GainExperienc_experience_id_521":"Sunderer Kill by Valkyrie Gunner",
  "GainExperienc_experience_id_522":"Lightning Kill by Valkyrie Gunne",
  "GainExperienc_experience_id_523":"Vanguard Kill by Valkyrie Gunner",
  "GainExperienc_experience_id_524":"Prowler Kill by Valkyrie Gunner",
  "GainExperienc_experience_id_525":"Reaver Kill by Valkyrie Gunner",
  "GainExperienc_experience_id_526":"Mosquito Kill by Valkyrie Gunner",
  "GainExperienc_experience_id_527":"Lib Kill by Valkyrie",
  "GainExperienc_experience_id_528":"Galaxy Kill by Valkyrie Gunner",
  "GainExperienc_experience_id_529":"Magrider Kill by Valkyrie Gunner",
  "GainExperienc_experience_id_530":"Scythe Kill by Valkyrie Gunner",
  "GainExperienc_experience_id_531":"Snowman Kill by Valkyrie Gunner",
  "GainExperienc_experience_id_532":"R Drone Kill by Valkyrie Gunner",
  "GainExperienc_experience_id_533":"Valkyrie Kill by Valkyrie Gunner",
  "GainExperienc_experience_id_534":"Chain Expl Assist: Phalanx",
  "GainExperienc_experience_id_535":"Chain Expl Assist: Drop Pod",
  "GainExperienc_experience_id_536":"Chain Expl Assist: Galaxy",
  "GainExperienc_experience_id_537":"Chain Expl Assist: Liberator",
  "GainExperienc_experience_id_538":"Chain Expl Assist: Lightning",
  "GainExperienc_experience_id_539":"Chain Expl Assist: Magrider",
  "GainExperienc_experience_id_540":"Chain Expl Assist: Mosquito",
  "GainExperienc_experience_id_541":"Chain Expl Assist: Prowler",
  "GainExperienc_experience_id_542":"Chain Expl Assist: Reaver",
  "GainExperienc_experience_id_543":"Chain Expl Assist: Scythe",
  "GainExperienc_experience_id_544":"Chain Expl Assist: Sunderer",
  "GainExperienc_experience_id_545":"Chain Expl Assist: Vanguard",
  "GainExperienc_experience_id_546":"Chain Expl Assist: Harasser",
  "GainExperienc_experience_id_547":"Chain Expl Assist: R Drone",
  "GainExperienc_experience_id_548":"Chain Expl Assist: Valkyrie",
  "GainExperienc_experience_id_550":"Concussion Grenade Assist",
  "GainExperienc_experience_id_551":"Concussion Grenade Squad Assist",
  "GainExperienc_experience_id_552":"EMP Grenade Assist",
  "GainExperienc_experience_id_553":"EMP Grenade Squad Assist",
  "GainExperienc_experience_id_554":"Flashbang Assist",
  "GainExperienc_experience_id_555":"Flashbang Squad Assist",
  "GainExperienc_experience_id_556":"Objective Pulse Defend",
  "GainExperienc_experience_id_557":"Objective Pulse Capture",
  "GainExperienc_experience_id_558":"Halloween Event NPC GreatP: Kill",
  "GainExperienc_experience_id_559":"Pumpkin Kill by Valkyrie Gunner",
  "GainExperienc_experience_id_560":"Pumpkin Kill by Sunderer Gunner",
  "GainExperienc_experience_id_561":"Pumpkin Kill by Magrider Gunner",
  "GainExperienc_experience_id_562":"Pumpkin Kill by Vanguard Gunner",
  "GainExperienc_experience_id_563":"Pumpkin Kill by Prowler Gunner",
  "GainExperienc_experience_id_564":"Pumpkin Kill by Liberator Gunner",
  "GainExperienc_experience_id_565":"Pumpkin Kill by Galaxy Gunner",
  "GainExperienc_experience_id_566":"Pumpkin Kill by Harasser Gunner",
  "GainExperienc_experience_id_567":"GPumpkin Kill by Sunder Gunner",
  "GainExperienc_experience_id_568":"GPumpkin Kill by Mag Gunner",
  "GainExperienc_experience_id_569":"GPumpkin Kill by Vang Gunner",
  "GainExperienc_experience_id_570":"GPumpkin Kill by Prow Gunner",
  "GainExperienc_experience_id_571":"GPumpkin Kill by Lib Gunner",
  "GainExperienc_experience_id_572":"GPumpkin Kill by Gal Gunner",
  "GainExperienc_experience_id_573":"GPumpkin Kill by Haras Gunner",
  "GainExperienc_experience_id_574":"Halloween Event NPC: Kill",
  "GainExperienc_experience_id_575":"Harasser Kill by Valkyrie Gunner",
  "GainExperienc_experience_id_576":"Valkyrie Kill by Harasser Gunner",
  "GainExperienc_experience_id_577":"Snowman kill by squad member",
  "GainExperienc_experience_id_578":"Gsnowman kill by squad member",
  "GainExperienc_experience_id_579":"Destroy Spitfire Turret",
  "GainExperienc_experience_id_580":"Vehicle Ram Kill - Spitfire Turret",
  "GainExperienc_experience_id_581":"Vehicle Repair - Spitfire Turret",
  "GainExperienc_experience_id_582":"Kill Assist - Spitfire Turret",
  "GainExperienc_experience_id_584":"Squad Repair - Spitfire Turret",
  "GainExperienc_experience_id_585":"Spot Kill - Spitfire Turret",
  "GainExperienc_experience_id_586":"Squad Spot Kill - Spitfire Turret",
  "GainExperienc_experience_id_591":"Kill Dummy NPC",
  "GainExperienc_experience_id_592":"Savior Kill (MAX)",
  "GainExperienc_experience_id_593":"Bounty Kill Bonus",
  "GainExperienc_experience_id_594":"Bounty Kill Cashed In",
  "GainExperienc_experience_id_595":"Bounty Kill Streak",
  "GainExperienc_experience_id_596":"Membership bonus xp",
  "GainExperienc_experience_id_597":"Victory Point XP",
  "GainExperienc_experience_id_598":"Continent Capture XP",
  "GainExperienc_experience_id_599":"Victory Point XP (-25%XP)",
  "GainExperienc_experience_id_600":"Victory Point XP (-50%XP)",
  "GainExperienc_experience_id_601":"Victory Point XP (-75%XP)",
  "GainExperienc_experience_id_602":"Victory Point XP (+50%XP)",
  "GainExperienc_experience_id_603":"Vehicle Ram Kill - Construction - Med",
  "GainExperienc_experience_id_604":"Kill/Destroy - Construction - Med",
  "GainExperienc_experience_id_605":"SquadRepair - Construction - Med",
  "GainExperienc_experience_id_606":"Repair - Construction - Med",
  "GainExperienc_experience_id_607":"KillAssist - Construction - Med",
  "GainExperienc_experience_id_609":"Spot Kill - Construction - Med ",
  "GainExperienc_experience_id_610":"Squad Spot Kill - Construction - Med",
  "GainExperienc_experience_id_615":"Vehicle Ram Kill - Construction - Small",
  "GainExperienc_experience_id_616":"Kill/Destroy - Construction - Small",
  "GainExperienc_experience_id_617":"SquadRepair - Construction - Sma",
  "GainExperienc_experience_id_618":"Repair - Construction - Small",
  "GainExperienc_experience_id_619":"KillAssist - Construction - Small",
  "GainExperienc_experience_id_621":"Spot Kill - Construction - Small ",
  "GainExperienc_experience_id_622":"Squad Spot Kill - Construction - Small",
  "GainExperienc_experience_id_627":"Vehicle Ram Kill - Construction - Large",
  "GainExperienc_experience_id_628":"Kill/Destroy - Construction - Large",
  "GainExperienc_experience_id_629":"SquadRepair - Construction - Lar",
  "GainExperienc_experience_id_630":"Repair - Construction - Large",
  "GainExperienc_experience_id_631":"KillAssist - Construction - Large",
  "GainExperienc_experience_id_633":"Spot Kill - Construction - Large ",
  "GainExperienc_experience_id_634":"Squad Spot Kill - Construction - Large",
  "GainExperienc_experience_id_639":"Vehicle Ram Kill - Construction - Core",
  "GainExperienc_experience_id_640":"Kill/Destroy - Construction - Core",
  "GainExperienc_experience_id_641":"SquadRepair - Construction - Cor",
  "GainExperienc_experience_id_642":"Repair - Construction - Core",
  "GainExperienc_experience_id_643":"KillAssist - Construction - Core",
  "GainExperienc_experience_id_645":"Spot Kill - Construction - Core ",
  "GainExperienc_experience_id_646":"Squad Spot Kill - Construction - Core",
  "GainExperienc_experience_id_651":"Vehicle Destruction - ANT",
  "GainExperienc_experience_id_652":"Vehicle Ram Kill - ANT",
  "GainExperienc_experience_id_653":"Vehicle Repair - ANT",
  "GainExperienc_experience_id_654":"Kill Assist - ANT",
  "GainExperienc_experience_id_656":"Squad Repair - ANT",
  "GainExperienc_experience_id_657":"ANT Kill by ANT Gunner",
  "GainExperienc_experience_id_658":"ANT Kill by Magrider Gunner",
  "GainExperienc_experience_id_659":"ANT Kill by Vanguard Gunner",
  "GainExperienc_experience_id_660":"ANT Kill by Prowler Gunner",
  "GainExperienc_experience_id_661":"ANT Kill by Lib Gunner",
  "GainExperienc_experience_id_662":"ANT Kill by Galaxy Gunner",
  "GainExperienc_experience_id_663":"Spot Kill - ANT",
  "GainExperienc_experience_id_664":"Squad Spot Kill - ANT",
  "GainExperienc_experience_id_665":"ANT Damage (Infantry vs Vehicle)",
  "GainExperienc_experience_id_666":"ANT Kill by Harasser Gunner",
  "GainExperienc_experience_id_671":"ANT Kill by Valkyrie Gunner",
  "GainExperienc_experience_id_672":"Chain Expl Assist: ANT",
  "GainExperienc_experience_id_673":"Bounty Kill Cashed In",
  "GainExperienc_experience_id_674":"Cortium Harvest",
  "GainExperienc_experience_id_675":"Cortium Deposit",
  "GainExperienc_experience_id_676":"Flash Kill by ANT Gunner",
  "GainExperienc_experience_id_677":"Galaxy Kill by ANT Gunner",
  "GainExperienc_experience_id_678":"Harasser Kill by ANT Gunner",
  "GainExperienc_experience_id_679":"Magrider Kill by ANT Gunner",
  "GainExperienc_experience_id_680":"Mosquito Kill by ANT Gunner",
  "GainExperienc_experience_id_681":"Player Kill by ANT Gunner",
  "GainExperienc_experience_id_682":"Prowler Kill by ANT Gunner",
  "GainExperienc_experience_id_683":"Pumpkin Kill by ANT Gunner",
  "GainExperienc_experience_id_684":"R Drone Kill by ANT Gunner",
  "GainExperienc_experience_id_685":"Reaver Kill by ANT Gunner",
  "GainExperienc_experience_id_686":"Scythe Kill by ANT Gunner",
  "GainExperienc_experience_id_687":"Snowman Kill by ANT Gunner",
  "GainExperienc_experience_id_688":"Sunderer Kill by ANT Gunner",
  "GainExperienc_experience_id_689":"Valkyrie Kill by ANT Gunner",
  "GainExperienc_experience_id_690":"Vanguard Kill by ANT Gunner",
  "GainExperienc_experience_id_693":"Kill Player - HIVE XP (Source)",
  "GainExperienc_experience_id_694":"Kill Player - HIVE XP (Target)",
  "GainExperienc_experience_id_695":"Kill Player Assist HIVE: Source",
  "GainExperienc_experience_id_696":"Kill Spawn Ass HIVE: Source",
  "GainExperienc_experience_id_697":"Heal Player HIVE: Source",
  "GainExperienc_experience_id_698":"MAX Repair HIVE: Source",
  "GainExperienc_experience_id_699":"Revive HIVE: Source",
  "GainExperienc_experience_id_701":"Destroy SecObj HIVE: Source",
  "GainExperienc_experience_id_702":"Destroy SecAss HIVE: Source",
  "GainExperienc_experience_id_703":"Vehicle Dest: Flash HIVE: Source",
  "GainExperienc_experience_id_705":"Transport Assist HIVE: Source",
  "GainExperienc_experience_id_706":"Vehicle Repair - Flash HIVE: Source",
  "GainExperienc_experience_id_707":"Resupply Player HIVE: Source",
  "GainExperienc_experience_id_708":"Kill Player Assist HIVE XP (Target)",
  "GainExperienc_experience_id_709":"Kill Spawn Ass HIVE XP (Target)",
  "GainExperienc_experience_id_710":"Heal Player HIVE XP (Target)",
  "GainExperienc_experience_id_711":"MAX Repair HIVE XP (Target)",
  "GainExperienc_experience_id_712":"Revive HIVE XP (Target)",
  "GainExperienc_experience_id_714":"Destroy SecObj HIVE XP (Target)",
  "GainExperienc_experience_id_715":"Destroy SecAss HIVE XP (Target)",
  "GainExperienc_experience_id_716":"Vehicle Dest: Flash HIVE XP (Target)",
  "GainExperienc_experience_id_718":"Transport Assist HIVE XP (Target)",
  "GainExperienc_experience_id_719":"Vehicle Repair - Flash HIVE XP (Target)",
  "GainExperienc_experience_id_720":"Resupply Player HIVE XP (Target)",
  "GainExperienc_experience_id_721":"Destroy Engineer Turret HIVE XP (Source)",
  "GainExperienc_experience_id_722":"Vehicle Destruction - Phalanx HIVE XP (Source)",
  "GainExperienc_experience_id_723":"Vehicle Destruction - Drop Pod HIVE XP (Source)",
  "GainExperienc_experience_id_724":"Vehicle Destruction - Galaxy HIVE XP (Source)",
  "GainExperienc_experience_id_725":"Vehicle Destruction - Liberator HIVE XP (Source)",
  "GainExperienc_experience_id_726":"Vehicle Destruction - Lightning HIVE XP (Source)",
  "GainExperienc_experience_id_727":"Vehicle Destruction - Magrider HIVE XP (Source)",
  "GainExperienc_experience_id_728":"Vehicle Destruction - Mosquito HIVE XP (Source)",
  "GainExperienc_experience_id_729":"Vehicle Destruction - Prowler HIVE XP (Source)",
  "GainExperienc_experience_id_730":"Vehicle Destruction - Reaver HIVE XP (Source)",
  "GainExperienc_experience_id_731":"Vehicle Destruction - Scythe HIVE XP (Source)",
  "GainExperienc_experience_id_732":"Vehicle Destruction - Sunderer HIVE XP (Source)",
  "GainExperienc_experience_id_733":"Vehicle Destruction - Vanguard HIVE XP (Source)",
  "GainExperienc_experience_id_734":"Vehicle Repair - Engi Turret HIVE XP (Source)",
  "GainExperienc_experience_id_735":"Vehicle Repair - Phalanx HIVE XP (Source)",
  "GainExperienc_experience_id_736":"Vehicle Repair - Drop Pod HIVE XP (Source)",
  "GainExperienc_experience_id_737":"Vehicle Repair - Galaxy HIVE XP (Source)",
  "GainExperienc_experience_id_738":"Vehicle Repair - Liberator HIVE XP (Source)",
  "GainExperienc_experience_id_739":"Vehicle Repair - Lightning HIVE XP (Source)",
  "GainExperienc_experience_id_740":"Vehicle Repair - Magrider HIVE XP (Source)",
  "GainExperienc_experience_id_741":"Destroy Engineer Turret HIVE XP (Target)",
  "GainExperienc_experience_id_742":"Vehicle Destruction - Phalanx HIVE XP (Target)",
  "GainExperienc_experience_id_743":"Vehicle Destruction - Drop Pod HIVE XP (Target)",
  "GainExperienc_experience_id_744":"Vehicle Destruction - Galaxy HIVE XP (Target)",
  "GainExperienc_experience_id_745":"Vehicle Destruction - Liberator HIVE XP (Target)",
  "GainExperienc_experience_id_746":"Vehicle Destruction - Lightning HIVE XP (Target)",
  "GainExperienc_experience_id_747":"Vehicle Destruction - Magrider HIVE XP (Target)",
  "GainExperienc_experience_id_748":"Vehicle Destruction - Mosquito HIVE XP (Target)",
  "GainExperienc_experience_id_749":"Vehicle Destruction - Prowler HIVE XP (Target)",
  "GainExperienc_experience_id_750":"Vehicle Destruction - Reaver HIVE XP (Target)",
  "GainExperienc_experience_id_751":"Vehicle Destruction - Scythe HIVE XP (Target)",
  "GainExperienc_experience_id_752":"Vehicle Destruction - Sunderer HIVE XP (Target)",
  "GainExperienc_experience_id_753":"Vehicle Destruction - Vanguard HIVE XP (Target)",
  "GainExperienc_experience_id_754":"Vehicle Repair - Engi Turret HIVE XP (Target)",
  "GainExperienc_experience_id_755":"Vehicle Repair - Phalanx HIVE XP (Target)",
  "GainExperienc_experience_id_756":"Vehicle Repair - Drop Pod HIVE XP (Target)",
  "GainExperienc_experience_id_757":"Vehicle Repair - Galaxy HIVE XP (Target)",
  "GainExperienc_experience_id_758":"Vehicle Repair - Liberator HIVE XP (Target)",
  "GainExperienc_experience_id_759":"Vehicle Repair - Lightning HIVE XP (Target)",
  "GainExperienc_experience_id_760":"Vehicle Repair - Magrider HIVE XP (Target)",
  "GainExperienc_experience_id_761":"Vehicle Repair - Mosquito HIVE XP (Source)",
  "GainExperienc_experience_id_762":"Vehicle Repair - Prowler HIVE XP (Source)",
  "GainExperienc_experience_id_763":"Vehicle Repair - Reaver HIVE XP (Source)",
  "GainExperienc_experience_id_764":"Vehicle Repair - Scythe HIVE XP (Source)",
  "GainExperienc_experience_id_765":"Vehicle Repair - Sunderer HIVE XP (Source)",
  "GainExperienc_experience_id_766":"Vehicle Repair - Vanguard HIVE XP (Source)",
  "GainExperienc_experience_id_767":"Kill Assist - Flash HIVE XP (Source)",
  "GainExperienc_experience_id_768":"Kill Assist - Engi Turret HIVE XP (Source)",
  "GainExperienc_experience_id_769":"Kill Assist - Phalanx HIVE XP (Source)",
  "GainExperienc_experience_id_770":"Kill Assist - Drop Pod HIVE XP (Source)",
  "GainExperienc_experience_id_771":"Kill Assist - Galaxy HIVE XP (Source)",
  "GainExperienc_experience_id_772":"Kill Assist - Liberator HIVE XP (Source)",
  "GainExperienc_experience_id_773":"Kill Assist - Lightning HIVE XP (Source)",
  "GainExperienc_experience_id_774":"Kill Assist - Magrider HIVE XP (Source)",
  "GainExperienc_experience_id_775":"Kill Assist - Mosquito HIVE XP (Source)",
  "GainExperienc_experience_id_776":"Kill Assist - Prowler HIVE XP (Source)",
  "GainExperienc_experience_id_777":"Kill Assist - Reaver HIVE XP (Source)",
  "GainExperienc_experience_id_778":"Kill Assist - Scythe HIVE XP (Source)",
  "GainExperienc_experience_id_779":"Kill Assist - Sunderer HIVE XP (Source)",
  "GainExperienc_experience_id_780":"Kill Assist - Vanguard HIVE XP (Source)",
  "GainExperienc_experience_id_781":"Vehicle Repair - Mosquito HIVE XP (Target)",
  "GainExperienc_experience_id_782":"Vehicle Repair - Prowler HIVE XP (Target)",
  "GainExperienc_experience_id_783":"Vehicle Repair - Reaver HIVE XP (Target)",
  "GainExperienc_experience_id_784":"Vehicle Repair - Scythe HIVE XP (Target)",
  "GainExperienc_experience_id_785":"Vehicle Repair - Sunderer HIVE XP (Target)",
  "GainExperienc_experience_id_786":"Vehicle Repair - Vanguard HIVE XP (Target)",
  "GainExperienc_experience_id_787":"Kill Assist - Flash HIVE XP (Target)",
  "GainExperienc_experience_id_788":"Kill Assist - Engi Turret HIVE XP (Target)",
  "GainExperienc_experience_id_789":"Kill Assist - Phalanx HIVE XP (Target)",
  "GainExperienc_experience_id_790":"Kill Assist - Drop Pod HIVE XP (Target)",
  "GainExperienc_experience_id_791":"Kill Assist - Galaxy HIVE XP (Target)",
  "GainExperienc_experience_id_792":"Kill Assist - Liberator HIVE XP (Target)",
  "GainExperienc_experience_id_793":"Kill Assist - Lightning HIVE XP (Target)",
  "GainExperienc_experience_id_794":"Kill Assist - Magrider HIVE XP (Target)",
  "GainExperienc_experience_id_795":"Kill Assist - Mosquito HIVE XP (Target)",
  "GainExperienc_experience_id_796":"Kill Assist - Prowler HIVE XP (Target)",
  "GainExperienc_experience_id_797":"Kill Assist - Reaver HIVE XP (Target)",
  "GainExperienc_experience_id_798":"Kill Assist - Scythe HIVE XP (Target)",
  "GainExperienc_experience_id_799":"Kill Assist - Sunderer HIVE XP (Target)",
  "GainExperienc_experience_id_800":"Kill Assist - Vanguard HIVE XP (Target)",
  "GainExperienc_experience_id_815":"Drop Pod Kill HIVE XP (Source)",
  "GainExperienc_experience_id_816":"Player Kill by Sunderer Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_817":"Player Kill by Magrider Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_818":"Player Kill by Vanguard Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_819":"Player Kill by Prowler Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_820":"Player Kill by Liberator Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_835":"Drop Pod Kill HIVE XP (Target)",
  "GainExperienc_experience_id_836":"Player Kill by Sunderer Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_837":"Player Kill by Magrider Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_838":"Player Kill by Vanguard Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_839":"Player Kill by Prowler Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_840":"Player Kill by Liberator Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_841":"Player Kill by Galaxy Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_842":"Flash Kill by Sunderer Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_843":"Sunderer Kill by Sunderer Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_844":"Lightning Kill by Sunderer Gunne HIVE XP (Source)",
  "GainExperienc_experience_id_845":"Magrider Kill by Sunderer Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_846":"Vanguard Kill by Sunderer Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_847":"Prowler Kill by Sunderer Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_848":"Scythe Kill by Sunderer Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_849":"Reaver Kill by Sunderer Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_850":"Mosquito Kill by Sunderer Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_851":"Lib Kill by Sunderer HIVE XP (Source)",
  "GainExperienc_experience_id_852":"Galaxy Kill by Sunderer Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_853":"Flash Kill by Magrider Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_854":"Sunderer Kill by Magrider Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_855":"Lightning Kill by Magrider Gunne HIVE XP (Source)",
  "GainExperienc_experience_id_856":"Vanguard Kill by Magrider Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_857":"Prowler Kill by Magrider Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_858":"Reaver Kill by Magrider Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_859":"Mosquito Kill by Magrider Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_860":"Lib Kill by Magrider HIVE XP (Source)",
  "GainExperienc_experience_id_861":"Player Kill by Galaxy Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_862":"Flash Kill by Sunderer Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_863":"Sunderer Kill by Sunderer Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_864":"Lightning Kill by Sunderer Gunne HIVE XP (Target)",
  "GainExperienc_experience_id_865":"Magrider Kill by Sunderer Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_866":"Vanguard Kill by Sunderer Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_867":"Prowler Kill by Sunderer Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_868":"Scythe Kill by Sunderer Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_869":"Reaver Kill by Sunderer Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_870":"Mosquito Kill by Sunderer Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_871":"Lib Kill by Sunderer HIVE XP (Target)",
  "GainExperienc_experience_id_872":"Galaxy Kill by Sunderer Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_873":"Flash Kill by Magrider Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_874":"Sunderer Kill by Magrider Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_875":"Lightning Kill by Magrider Gunne HIVE XP (Target)",
  "GainExperienc_experience_id_876":"Vanguard Kill by Magrider Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_877":"Prowler Kill by Magrider Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_878":"Reaver Kill by Magrider Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_879":"Mosquito Kill by Magrider Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_880":"Lib Kill by Magrider HIVE XP (Target)",
  "GainExperienc_experience_id_881":"Galaxy Kill by Magrider Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_882":"Flash Kill by Vanguard Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_883":"Sunderer Kill by Vanguard Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_884":"Lightning Kill by Vanguard Gunne HIVE XP (Source)",
  "GainExperienc_experience_id_885":"Magrider Kill by Vanguard Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_886":"Prowler Kill by Vanguard Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_887":"Scythe Kill by Vanguard Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_888":"Mosquito Kill by Vanguard Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_889":"Lib Kill by Vanguard HIVE XP (Source)",
  "GainExperienc_experience_id_890":"Galaxy Kill by Vanguard Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_891":"Flash Kill by Prowler Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_892":"Sunderer Kill by Prowler Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_893":"Lightning Kill by Prowler Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_894":"Magrider Kill by Prowler Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_895":"Vanguard Kill by Prowler Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_896":"Scythe Kill by Prowler Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_897":"Reaver Kill by Prowler Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_898":"Liberator Kill by Prowler Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_899":"Galaxy Kill by Prowler Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_900":"Galaxy Kill by Magrider Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_901":"Flash Kill by Vanguard Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_902":"Sunderer Kill by Vanguard Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_903":"Lightning Kill by Vanguard Gunne HIVE XP (Target)",
  "GainExperienc_experience_id_904":"Magrider Kill by Vanguard Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_905":"Prowler Kill by Vanguard Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_906":"Scythe Kill by Vanguard Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_907":"Mosquito Kill by Vanguard Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_908":"Lib Kill by Vanguard HIVE XP (Target)",
  "GainExperienc_experience_id_909":"Galaxy Kill by Vanguard Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_910":"Flash Kill by Prowler Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_911":"Sunderer Kill by Prowler Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_912":"Lightning Kill by Prowler Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_913":"Magrider Kill by Prowler Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_914":"Vanguard Kill by Prowler Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_915":"Scythe Kill by Prowler Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_916":"Reaver Kill by Prowler Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_917":"Liberator Kill by Prowler Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_918":"Galaxy Kill by Prowler Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_919":"Flash Kill by Liberator Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_920":"Sunderer Kill by Lib Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_921":"Lightning Kill by Liberator Gunn HIVE XP (Source)",
  "GainExperienc_experience_id_922":"Magrider Kill by Lib Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_923":"Vanguard Kill by Lib Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_924":"Prowler Kill by Liberator Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_925":"Scythe Kill by Liberator Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_926":"Reaver Kill by Liberator Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_927":"Mosquito Kill by Lib Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_928":"Lib Kill by Liberator HIVE XP (Source)",
  "GainExperienc_experience_id_929":"Galaxy Kill by Liberator Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_930":"Flash Kill by Galaxy Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_931":"Sunderer Kill by Galaxy Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_932":"Lightning Kill by Galaxy Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_933":"Magrider Kill by Galaxy Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_934":"Vanguard Kill by Galaxy Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_935":"Prowler Kill by Galaxy Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_936":"Scythe Kill by Galaxy Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_937":"Reaver Kill by Galaxy Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_938":"Mosquito Kill by Galaxy Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_939":"Flash Kill by Liberator Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_940":"Sunderer Kill by Lib Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_941":"Lightning Kill by Liberator Gunn HIVE XP (Target)",
  "GainExperienc_experience_id_942":"Magrider Kill by Lib Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_943":"Vanguard Kill by Lib Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_944":"Prowler Kill by Liberator Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_945":"Scythe Kill by Liberator Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_946":"Reaver Kill by Liberator Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_947":"Mosquito Kill by Lib Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_948":"Lib Kill by Liberator HIVE XP (Target)",
  "GainExperienc_experience_id_949":"Galaxy Kill by Liberator Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_950":"Flash Kill by Galaxy Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_951":"Sunderer Kill by Galaxy Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_952":"Lightning Kill by Galaxy Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_953":"Magrider Kill by Galaxy Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_954":"Vanguard Kill by Galaxy Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_955":"Prowler Kill by Galaxy Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_956":"Scythe Kill by Galaxy Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_957":"Reaver Kill by Galaxy Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_958":"Mosquito Kill by Galaxy Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_959":"LibKill by Galaxy Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_960":"Galaxy Kill by Galaxy Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_961":"Terminal Kill HIVE XP (Source)",
  "GainExperienc_experience_id_962":"Terminal Repair HIVE XP (Source)",
  "GainExperienc_experience_id_966":"Galaxy Damage HIVE XP (Source)",
  "GainExperienc_experience_id_967":"Liberator Damage HIVE XP (Source)",
  "GainExperienc_experience_id_969":"Mosquito Damage HIVE XP (Source)",
  "GainExperienc_experience_id_970":"Reaver Damage HIVE XP (Source)",
  "GainExperienc_experience_id_971":"Scythe Damage HIVE XP (Source)",
  "GainExperienc_experience_id_974":"Vehicle Repair - Harasser HIVE XP (Source)",
  "GainExperienc_experience_id_975":"Kill Assist - Harasser HIVE XP (Source)",
  "GainExperienc_experience_id_977":"Spot Kill - Harasser HIVE XP (Source)",
  "GainExperienc_experience_id_978":"LibKill by Galaxy Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_979":"Galaxy Kill by Galaxy Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_980":"Terminal Kill HIVE XP (Target)",
  "GainExperienc_experience_id_981":"Terminal Repair HIVE XP (Target)",
  "GainExperienc_experience_id_985":"Galaxy Damage HIVE XP (Target)",
  "GainExperienc_experience_id_986":"Liberator Damage HIVE XP (Target)",
  "GainExperienc_experience_id_988":"Mosquito Damage HIVE XP (Target)",
  "GainExperienc_experience_id_989":"Reaver Damage HIVE XP (Target)",
  "GainExperienc_experience_id_990":"Scythe Damage HIVE XP (Target)",
  "GainExperienc_experience_id_993":"Vehicle Repair - Harasser HIVE XP (Target)",
  "GainExperienc_experience_id_994":"Kill Assist - Harasser HIVE XP (Target)",
  "GainExperienc_experience_id_996":"Spot Kill - Harasser HIVE XP (Target)",
  "GainExperienc_experience_id_997":"Harasser Kill by Sunderer Gunne HIVE XP (Source)",
  "GainExperienc_experience_id_998":"Harasser Kill by Magrider Gunne HIVE XP (Source)",
  "GainExperienc_experience_id_999":"Harasser Kill by Vanguard Gunne HIVE XP (Source)",
  "GainExperienc_experience_id_1000":"Harasser Kill by Prowler Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_1001":"Harasser Kill by Liberator Gunn HIVE XP (Source)",
  "GainExperienc_experience_id_1002":"Harasser Kill by Galaxy Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_1003":"Player Kill by Harasser Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_1004":"Flash Kill by Harasser Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_1005":"Sunderer Kill by Harasser Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_1006":"Lightning Kill by Harasser Gunne HIVE XP (Source)",
  "GainExperienc_experience_id_1007":"Vanguard Kill by Harasser Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_1008":"Prowler Kill by Harasser Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_1009":"Reaver Kill by Harasser Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_1010":"Mosquito Kill by Harasser Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_1011":"Lib Kill by Harasser HIVE XP (Source)",
  "GainExperienc_experience_id_1012":"Galaxy Kill by Harasser Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_1013":"Harasser Kill by Harasser Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_1014":"Magrider Kill by Harasser Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_1015":"Scythe Kill by Harasser Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_1016":"Tank Mine Despawn/Defusal HIVE XP (Source)",
  "GainExperienc_experience_id_1017":"Harasser Kill by Sunderer Gunne HIVE XP (Target)",
  "GainExperienc_experience_id_1018":"Harasser Kill by Magrider Gunne HIVE XP (Target)",
  "GainExperienc_experience_id_1019":"Harasser Kill by Vanguard Gunne HIVE XP (Target)",
  "GainExperienc_experience_id_1020":"Harasser Kill by Prowler Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_1021":"Harasser Kill by Liberator Gunn HIVE XP (Target)",
  "GainExperienc_experience_id_1022":"Harasser Kill by Galaxy Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_1023":"Player Kill by Harasser Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_1024":"Flash Kill by Harasser Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_1025":"Sunderer Kill by Harasser Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_1026":"Lightning Kill by Harasser Gunne HIVE XP (Target)",
  "GainExperienc_experience_id_1027":"Vanguard Kill by Harasser Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_1028":"Prowler Kill by Harasser Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_1029":"Reaver Kill by Harasser Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_1030":"Mosquito Kill by Harasser Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_1031":"Lib Kill by Harasser HIVE XP (Target)",
  "GainExperienc_experience_id_1032":"Galaxy Kill by Harasser Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_1033":"Harasser Kill by Harasser Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_1034":"Magrider Kill by Harasser Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_1035":"Scythe Kill by Harasser Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_1036":"Tank Mine Despawn/Defusal HIVE XP (Target)",
  "GainExperienc_experience_id_1037":"Vehicle Gunner Kill Share - Infantry HIVE XP (Source)",
  "GainExperienc_experience_id_1038":"Vehicle Gunner Kill Share - Flash HIVE XP (Source)",
  "GainExperienc_experience_id_1039":"Vehicle Gunner Kill Share - Engineer Turret HIVE XP (Source)",
  "GainExperienc_experience_id_1040":"Vehicle Gunner Kill Share - Phalanx HIVE XP (Source)",
  "GainExperienc_experience_id_1041":"Vehicle Gunner Kill Share - Drop Pod HIVE XP (Source)",
  "GainExperienc_experience_id_1042":"Vehicle Gunner Kill Share - Galaxy HIVE XP (Source)",
  "GainExperienc_experience_id_1043":"Vehicle Gunner Kill Share - Liberator HIVE XP (Source)",
  "GainExperienc_experience_id_1044":"Vehicle Gunner Kill Share - Lightning HIVE XP (Source)",
  "GainExperienc_experience_id_1045":"Vehicle Gunner Kill Share - Magrider HIVE XP (Source)",
  "GainExperienc_experience_id_1046":"Vehicle Gunner Kill Share - Mosquito HIVE XP (Source)",
  "GainExperienc_experience_id_1047":"Vehicle Gunner Kill Share - Prowler HIVE XP (Source)",
  "GainExperienc_experience_id_1048":"Vehicle Gunner Kill Share - Reaver HIVE XP (Source)",
  "GainExperienc_experience_id_1049":"Vehicle Gunner Kill Share - Scythe HIVE XP (Source)",
  "GainExperienc_experience_id_1050":"Vehicle Gunner Kill Share - Sunderer HIVE XP (Source)",
  "GainExperienc_experience_id_1051":"Vehicle Gunner Kill Share - Vanguard HIVE XP (Source)",
  "GainExperienc_experience_id_1052":"Vehicle Gunner Kill Share - Harasser HIVE XP (Source)",
  "GainExperienc_experience_id_1053":"Vehicle Gunner Kill Assist Share - Infantry HIVE XP (Source)",
  "GainExperienc_experience_id_1054":"Vehicle Gunner Kill Assist Share - Flash HIVE XP (Source)",
  "GainExperienc_experience_id_1055":"Vehicle Gunner Kill Assist Share - Engi Turret HIVE XP (Source)",
  "GainExperienc_experience_id_1056":"Vehicle Gunner Kill Assist Share - Phalanx HIVE XP (Source)",
  "GainExperienc_experience_id_1057":"Vehicle Gunner Kill Share - Infantry HIVE XP (Target)",
  "GainExperienc_experience_id_1058":"Vehicle Gunner Kill Share - Flash HIVE XP (Target)",
  "GainExperienc_experience_id_1059":"Vehicle Gunner Kill Share - Engineer Turret HIVE XP (Target)",
  "GainExperienc_experience_id_1060":"Vehicle Gunner Kill Share - Phalanx HIVE XP (Target)",
  "GainExperienc_experience_id_1061":"Vehicle Gunner Kill Share - Drop Pod HIVE XP (Target)",
  "GainExperienc_experience_id_1062":"Vehicle Gunner Kill Share - Galaxy HIVE XP (Target)",
  "GainExperienc_experience_id_1063":"Vehicle Gunner Kill Share - Liberator HIVE XP (Target)",
  "GainExperienc_experience_id_1064":"Vehicle Gunner Kill Share - Lightning HIVE XP (Target)",
  "GainExperienc_experience_id_1065":"Vehicle Gunner Kill Share - Magrider HIVE XP (Target)",
  "GainExperienc_experience_id_1066":"Vehicle Gunner Kill Share - Mosquito HIVE XP (Target)",
  "GainExperienc_experience_id_1067":"Vehicle Gunner Kill Share - Prowler HIVE XP (Target)",
  "GainExperienc_experience_id_1068":"Vehicle Gunner Kill Share - Reaver HIVE XP (Target)",
  "GainExperienc_experience_id_1069":"Vehicle Gunner Kill Share - Scythe HIVE XP (Target)",
  "GainExperienc_experience_id_1070":"Vehicle Gunner Kill Share - Sunderer HIVE XP (Target)",
  "GainExperienc_experience_id_1071":"Vehicle Gunner Kill Share - Vanguard HIVE XP (Target)",
  "GainExperienc_experience_id_1072":"Vehicle Gunner Kill Share - Harasser HIVE XP (Target)",
  "GainExperienc_experience_id_1073":"Vehicle Gunner Kill Assist Share - Infantry HIVE XP (Target)",
  "GainExperienc_experience_id_1074":"Vehicle Gunner Kill Assist Share - Flash HIVE XP (Target)",
  "GainExperienc_experience_id_1075":"Vehicle Gunner Kill Assist Share - Engi Turret HIVE XP (Target)",
  "GainExperienc_experience_id_1076":"Vehicle Gunner Kill Assist Share - Phalanx HIVE XP (Target)",
  "GainExperienc_experience_id_1077":"Vehicle Gunner Kill Assist Share - Drop Pod HIVE XP (Source)",
  "GainExperienc_experience_id_1078":"Vehicle Gunner Kill Assist Share - Galaxy HIVE XP (Source)",
  "GainExperienc_experience_id_1079":"Vehicle Gunner Kill Assist Share - Liberator HIVE XP (Source)",
  "GainExperienc_experience_id_1080":"Vehicle Gunner Kill Assist Share - Lightning HIVE XP (Source)",
  "GainExperienc_experience_id_1081":"Vehicle Gunner Kill Assist Share - Magrider HIVE XP (Source)",
  "GainExperienc_experience_id_1082":"Vehicle Gunner Kill Assist Share - Mosquito HIVE XP (Source)",
  "GainExperienc_experience_id_1083":"Vehicle Gunner Kill Assist Share - Prowler HIVE XP (Source)",
  "GainExperienc_experience_id_1084":"Vehicle Gunner Kill Assist Share - Reaver HIVE XP (Source)",
  "GainExperienc_experience_id_1085":"Vehicle Gunner Kill Assist Share - Scythe HIVE XP (Source)",
  "GainExperienc_experience_id_1086":"Vehicle Gunner Kill Assist Share - Sunderer HIVE XP (Source)",
  "GainExperienc_experience_id_1087":"Vehicle Gunner Kill Assist Share - Vanguard HIVE XP (Source)",
  "GainExperienc_experience_id_1088":"Vehicle Gunner Kill Assist Share - Harasser HIVE XP (Source)",
  "GainExperienc_experience_id_1089":"Vehicle Passenger Kill Share - Infantry HIVE XP (Source)",
  "GainExperienc_experience_id_1090":"Vehicle Passenger Kill Share - Flash HIVE XP (Source)",
  "GainExperienc_experience_id_1091":"Vehicle Passenger Kill Share - Engineer Turret HIVE XP (Source)",
  "GainExperienc_experience_id_1092":"Vehicle Passenger Kill Share - Phalanx HIVE XP (Source)",
  "GainExperienc_experience_id_1093":"Vehicle Passenger Kill Share - Drop Pod HIVE XP (Source)",
  "GainExperienc_experience_id_1094":"Vehicle Passenger Kill Share - Galaxy HIVE XP (Source)",
  "GainExperienc_experience_id_1095":"Vehicle Passenger Kill Share - Liberator HIVE XP (Source)",
  "GainExperienc_experience_id_1096":"Vehicle Passenger Kill Share - Lightning HIVE XP (Source)",
  "GainExperienc_experience_id_1097":"Vehicle Gunner Kill Assist Share - Drop Pod HIVE XP (Target)",
  "GainExperienc_experience_id_1098":"Vehicle Gunner Kill Assist Share - Galaxy HIVE XP (Target)",
  "GainExperienc_experience_id_1099":"Vehicle Gunner Kill Assist Share - Liberator HIVE XP (Target)",
  "GainExperienc_experience_id_1100":"Vehicle Gunner Kill Assist Share - Lightning HIVE XP (Target)",
  "GainExperienc_experience_id_1101":"Vehicle Gunner Kill Assist Share - Magrider HIVE XP (Target)",
  "GainExperienc_experience_id_1102":"Vehicle Gunner Kill Assist Share - Mosquito HIVE XP (Target)",
  "GainExperienc_experience_id_1103":"Vehicle Gunner Kill Assist Share - Prowler HIVE XP (Target)",
  "GainExperienc_experience_id_1104":"Vehicle Gunner Kill Assist Share - Reaver HIVE XP (Target)",
  "GainExperienc_experience_id_1105":"Vehicle Gunner Kill Assist Share - Scythe HIVE XP (Target)",
  "GainExperienc_experience_id_1106":"Vehicle Gunner Kill Assist Share - Sunderer HIVE XP (Target)",
  "GainExperienc_experience_id_1107":"Vehicle Gunner Kill Assist Share - Vanguard HIVE XP (Target)",
  "GainExperienc_experience_id_1108":"Vehicle Gunner Kill Assist Share - Harasser HIVE XP (Target)",
  "GainExperienc_experience_id_1109":"Vehicle Passenger Kill Share - Infantry HIVE XP (Target)",
  "GainExperienc_experience_id_1110":"Vehicle Passenger Kill Share - Flash HIVE XP (Target)",
  "GainExperienc_experience_id_1111":"Vehicle Passenger Kill Share - Engineer Turret HIVE XP (Target)",
  "GainExperienc_experience_id_1112":"Vehicle Passenger Kill Share - Phalanx HIVE XP (Target)",
  "GainExperienc_experience_id_1113":"Vehicle Passenger Kill Share - Drop Pod HIVE XP (Target)",
  "GainExperienc_experience_id_1114":"Vehicle Passenger Kill Share - Galaxy HIVE XP (Target)",
  "GainExperienc_experience_id_1115":"Vehicle Passenger Kill Share - Liberator HIVE XP (Target)",
  "GainExperienc_experience_id_1116":"Vehicle Passenger Kill Share - Lightning HIVE XP (Target)",
  "GainExperienc_experience_id_1117":"Vehicle Passenger Kill Share - Magrider HIVE XP (Source)",
  "GainExperienc_experience_id_1118":"Vehicle Passenger Kill Share - Mosquito HIVE XP (Source)",
  "GainExperienc_experience_id_1119":"Vehicle Passenger Kill Share - Prowler HIVE XP (Source)",
  "GainExperienc_experience_id_1120":"Vehicle Passenger Kill Share - Reaver HIVE XP (Source)",
  "GainExperienc_experience_id_1121":"Vehicle Passenger Kill Share - Scythe HIVE XP (Source)",
  "GainExperienc_experience_id_1122":"Vehicle Passenger Kill Share - Sunderer HIVE XP (Source)",
  "GainExperienc_experience_id_1123":"Vehicle Passenger Kill Share - Vanguard HIVE XP (Source)",
  "GainExperienc_experience_id_1124":"Vehicle Passenger Kill Share - Harasser HIVE XP (Source)",
  "GainExperienc_experience_id_1125":"Vehicle Driver Kill Assist Share - Infantry HIVE XP (Source)",
  "GainExperienc_experience_id_1126":"Vehicle Driver Kill Assist Share - Flash HIVE XP (Source)",
  "GainExperienc_experience_id_1127":"Vehicle Driver Kill Assist Share - Engi Turret HIVE XP (Source)",
  "GainExperienc_experience_id_1128":"Vehicle Driver Kill Assist Share - Phalanx HIVE XP (Source)",
  "GainExperienc_experience_id_1129":"Vehicle Driver Kill Assist Share - Drop Pod HIVE XP (Source)",
  "GainExperienc_experience_id_1130":"Vehicle Driver Kill Assist Share - Galaxy HIVE XP (Source)",
  "GainExperienc_experience_id_1131":"Vehicle Driver Kill Assist Share - Liberator HIVE XP (Source)",
  "GainExperienc_experience_id_1132":"Vehicle Driver Kill Assist Share - Lightning HIVE XP (Source)",
  "GainExperienc_experience_id_1133":"Vehicle Driver Kill Assist Share - Magrider HIVE XP (Source)",
  "GainExperienc_experience_id_1134":"Vehicle Driver Kill Assist Share - Mosquito HIVE XP (Source)",
  "GainExperienc_experience_id_1135":"Vehicle Driver Kill Assist Share - Prowler HIVE XP (Source)",
  "GainExperienc_experience_id_1136":"Vehicle Driver Kill Assist Share - Reaver HIVE XP (Source)",
  "GainExperienc_experience_id_1137":"Vehicle Passenger Kill Share - Magrider HIVE XP (Target)",
  "GainExperienc_experience_id_1138":"Vehicle Passenger Kill Share - Mosquito HIVE XP (Target)",
  "GainExperienc_experience_id_1139":"Vehicle Passenger Kill Share - Prowler HIVE XP (Target)",
  "GainExperienc_experience_id_1140":"Vehicle Passenger Kill Share - Reaver HIVE XP (Target)",
  "GainExperienc_experience_id_1141":"Vehicle Passenger Kill Share - Scythe HIVE XP (Target)",
  "GainExperienc_experience_id_1142":"Vehicle Passenger Kill Share - Sunderer HIVE XP (Target)",
  "GainExperienc_experience_id_1143":"Vehicle Passenger Kill Share - Vanguard HIVE XP (Target)",
  "GainExperienc_experience_id_1144":"Vehicle Passenger Kill Share - Harasser HIVE XP (Target)",
  "GainExperienc_experience_id_1145":"Vehicle Driver Kill Assist Share - Infantry HIVE XP (Target)",
  "GainExperienc_experience_id_1146":"Vehicle Driver Kill Assist Share - Flash HIVE XP (Target)",
  "GainExperienc_experience_id_1147":"Vehicle Driver Kill Assist Share - Engi Turret HIVE XP (Target)",
  "GainExperienc_experience_id_1148":"Vehicle Driver Kill Assist Share - Phalanx HIVE XP (Target)",
  "GainExperienc_experience_id_1149":"Vehicle Driver Kill Assist Share - Drop Pod HIVE XP (Target)",
  "GainExperienc_experience_id_1150":"Vehicle Driver Kill Assist Share - Galaxy HIVE XP (Target)",
  "GainExperienc_experience_id_1151":"Vehicle Driver Kill Assist Share - Liberator HIVE XP (Target)",
  "GainExperienc_experience_id_1152":"Vehicle Driver Kill Assist Share - Lightning HIVE XP (Target)",
  "GainExperienc_experience_id_1153":"Vehicle Driver Kill Assist Share - Magrider HIVE XP (Target)",
  "GainExperienc_experience_id_1154":"Vehicle Driver Kill Assist Share - Mosquito HIVE XP (Target)",
  "GainExperienc_experience_id_1155":"Vehicle Driver Kill Assist Share - Prowler HIVE XP (Target)",
  "GainExperienc_experience_id_1156":"Vehicle Driver Kill Assist Share - Reaver HIVE XP (Target)",
  "GainExperienc_experience_id_1157":"Vehicle Driver Kill Assist Share - Scythe HIVE XP (Source)",
  "GainExperienc_experience_id_1158":"Vehicle Driver Kill Assist Share - Sunderer HIVE XP (Source)",
  "GainExperienc_experience_id_1159":"Vehicle Driver Kill Assist Share - Vanguard HIVE XP (Source)",
  "GainExperienc_experience_id_1160":"Vehicle Driver Kill Assist Share - Harasser HIVE XP (Source)",
  "GainExperienc_experience_id_1161":"Valkyrie Kill by Sunderer Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_1162":"Valkyrie Kill by Magrider Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_1163":"Valkyrie Kill by Vanguard Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_1164":"Valkyrie Kill by Prowler Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_1165":"Valkyrie Kill by Liberator Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_1166":"Valkyrie Kill by Galaxy Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_1167":"Player Kill by Valkyrie Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_1168":"Vehicle Gunner Kill Share - Valkyrie HIVE XP (Source)",
  "GainExperienc_experience_id_1169":"Vehicle Gunner Kill Assist Share - Valkyrie HIVE XP (Source)",
  "GainExperienc_experience_id_1170":"Vehicle Passenger Kill Share - Valkyrie HIVE XP (Source)",
  "GainExperienc_experience_id_1171":"Vehicle Driver Kill Assist Share - Valkyrie HIVE XP (Source)",
  "GainExperienc_experience_id_1172":"Flash Kill by Valkyrie Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_1173":"Sunderer Kill by Valkyrie Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_1174":"Lightning Kill by Valkyrie Gunne HIVE XP (Source)",
  "GainExperienc_experience_id_1175":"Vanguard Kill by Valkyrie Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_1176":"Prowler Kill by Valkyrie Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_1177":"Vehicle Driver Kill Assist Share - Scythe HIVE XP (Target)",
  "GainExperienc_experience_id_1178":"Vehicle Driver Kill Assist Share - Sunderer HIVE XP (Target)",
  "GainExperienc_experience_id_1179":"Vehicle Driver Kill Assist Share - Vanguard HIVE XP (Target)",
  "GainExperienc_experience_id_1180":"Vehicle Driver Kill Assist Share - Harasser HIVE XP (Target)",
  "GainExperienc_experience_id_1181":"Valkyrie Kill by Sunderer Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_1182":"Valkyrie Kill by Magrider Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_1183":"Valkyrie Kill by Vanguard Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_1184":"Valkyrie Kill by Prowler Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_1185":"Valkyrie Kill by Liberator Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_1186":"Valkyrie Kill by Galaxy Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_1187":"Player Kill by Valkyrie Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_1188":"Vehicle Gunner Kill Share - Valkyrie HIVE XP (Target)",
  "GainExperienc_experience_id_1189":"Vehicle Gunner Kill Assist Share - Valkyrie HIVE XP (Target)",
  "GainExperienc_experience_id_1190":"Vehicle Passenger Kill Share - Valkyrie HIVE XP (Target)",
  "GainExperienc_experience_id_1191":"Vehicle Driver Kill Assist Share - Valkyrie HIVE XP (Target)",
  "GainExperienc_experience_id_1192":"Flash Kill by Valkyrie Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_1193":"Sunderer Kill by Valkyrie Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_1194":"Lightning Kill by Valkyrie Gunne HIVE XP (Target)",
  "GainExperienc_experience_id_1195":"Vanguard Kill by Valkyrie Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_1196":"Prowler Kill by Valkyrie Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_1197":"Reaver Kill by Valkyrie Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_1198":"Mosquito Kill by Valkyrie Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_1199":"Lib Kill by Valkyrie HIVE XP (Source)",
  "GainExperienc_experience_id_1200":"Galaxy Kill by Valkyrie Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_1201":"Magrider Kill by Valkyrie Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_1202":"Scythe Kill by Valkyrie Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_1203":"Snowman Kill by Valkyrie Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_1204":"Valkyrie Kill by Valkyrie Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_1205":"Harasser Kill by Valkyrie Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_1206":"Valkyrie Kill by Harasser Gunner HIVE XP (Source)",
  "GainExperienc_experience_id_1207":"Destroy Spitfire Turret HIVE XP (Source)",
  "GainExperienc_experience_id_1208":"Vehicle Gunner Kill Share - Spitfire HIVE XP (Source)",
  "GainExperienc_experience_id_1209":"Vehicle Gunner Kill Assist Share - Spitfire HIVE XP (Source)",
  "GainExperienc_experience_id_1210":"Vehicle Passenger Kill Share - Spitfire HIVE XP (Source)",
  "GainExperienc_experience_id_1211":"Vehicle Driver Kill Assist Share - Engi Turret HIVE XP (Source)",
  "GainExperienc_experience_id_1212":"Kill/Destroy - Construction - Med HIVE XP (Source)",
  "GainExperienc_experience_id_1214":"Repair - Construction - Med HIVE XP (Source)",
  "GainExperienc_experience_id_1215":"KillAssist - Construction - Med HIVE XP (Source)",
  "GainExperienc_experience_id_1217":"Reaver Kill by Valkyrie Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_1218":"Mosquito Kill by Valkyrie Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_1219":"Lib Kill by Valkyrie HIVE XP (Target)",
  "GainExperienc_experience_id_1220":"Galaxy Kill by Valkyrie Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_1221":"Magrider Kill by Valkyrie Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_1222":"Scythe Kill by Valkyrie Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_1223":"Snowman Kill by Valkyrie Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_1224":"Valkyrie Kill by Valkyrie Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_1225":"Harasser Kill by Valkyrie Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_1226":"Valkyrie Kill by Harasser Gunner HIVE XP (Target)",
  "GainExperienc_experience_id_1227":"Destroy Spitfire Turret HIVE XP (Target)",
  "GainExperienc_experience_id_1228":"Vehicle Gunner Kill Share - Spitfire HIVE XP (Target)",
  "GainExperienc_experience_id_1229":"Vehicle Gunner Kill Assist Share - Spitfire HIVE XP (Target)",
  "GainExperienc_experience_id_1230":"Vehicle Passenger Kill Share - Spitfire HIVE XP (Target)",
  "GainExperienc_experience_id_1231":"Vehicle Driver Kill Assist Share - Engi Turret HIVE XP (Target)",
  "GainExperienc_experience_id_1232":"Kill/Destroy - Construction - Med HIVE XP (Target)",
  "GainExperienc_experience_id_1234":"Repair - Construction - Med HIVE XP (Target)",
  "GainExperienc_experience_id_1235":"KillAssist - Construction - Med HIVE XP (Target)",
  "GainExperienc_experience_id_1237":"Spot Kill - Construction - Med  HIVE XP (Source)",
  "GainExperienc_experience_id_1238":"Gunner Kill Share - Construction - Med HIVE XP (Source)",
  "GainExperienc_experience_id_1239":"Gunner Kill Assist Share - Construction - Med HIVE XP (Source)",
  "GainExperienc_experience_id_1240":"Vehicle Passenger Kill Share - Construction - Med HIVE XP (Source)",
  "GainExperienc_experience_id_1241":"Driver Kill Aassist Share - Construction - Med HIVE XP (Source)",
  "GainExperienc_experience_id_1242":"Vehicle Ram Kill - Construction - Small HIVE XP (Source)",
  "GainExperienc_experience_id_1243":"Kill/Destroy - Construction - Small HIVE XP (Source)",
  "GainExperienc_experience_id_1245":"Repair - Construction - Small HIVE XP (Source)",
  "GainExperienc_experience_id_1246":"KillAssist - Construction - Small HIVE XP (Source)",
  "GainExperienc_experience_id_1248":"Spot Kill - Construction - Small  HIVE XP (Source)",
  "GainExperienc_experience_id_1249":"Gunner Kill Share - Construction - Small HIVE XP (Source)",
  "GainExperienc_experience_id_1250":"Gunner Kill Assist Share - Construction - Small HIVE XP (Source)",
  "GainExperienc_experience_id_1251":"Vehicle Passenger Kill Share - Construction - Small HIVE XP (Source)",
  "GainExperienc_experience_id_1252":"Driver Kill Aassist Share - Construction - Small HIVE XP (Source)",
  "GainExperienc_experience_id_1253":"Vehicle Ram Kill - Construction - Large HIVE XP (Source)",
  "GainExperienc_experience_id_1254":"Kill/Destroy - Construction - Large HIVE XP (Source)",
  "GainExperienc_experience_id_1255":"Spot Kill - Construction - Med  HIVE XP (Target)",
  "GainExperienc_experience_id_1256":"Gunner Kill Share - Construction - Med HIVE XP (Target)",
  "GainExperienc_experience_id_1257":"Gunner Kill Assist Share - Construction - Med HIVE XP (Target)",
  "GainExperienc_experience_id_1258":"Vehicle Passenger Kill Share - Construction - Med HIVE XP (Target)",
  "GainExperienc_experience_id_1259":"Driver Kill Aassist Share - Construction - Med HIVE XP (Target)",
  "GainExperienc_experience_id_1260":"Vehicle Ram Kill - Construction - Small HIVE XP (Target)",
  "GainExperienc_experience_id_1261":"Kill/Destroy - Construction - Small HIVE XP (Target)",
  "GainExperienc_experience_id_1263":"Repair - Construction - Small HIVE XP (Target)",
  "GainExperienc_experience_id_1264":"KillAssist - Construction - Small HIVE XP (Target)",
  "GainExperienc_experience_id_1266":"Spot Kill - Construction - Small  HIVE XP (Target)",
  "GainExperienc_experience_id_1267":"Gunner Kill Share - Construction - Small HIVE XP (Target)",
  "GainExperienc_experience_id_1268":"Gunner Kill Assist Share - Construction - Small HIVE XP (Target)",
  "GainExperienc_experience_id_1269":"Vehicle Passenger Kill Share - Construction - Small HIVE XP (Target)",
  "GainExperienc_experience_id_1270":"Driver Kill Aassist Share - Construction - Small HIVE XP (Target)",
  "GainExperienc_experience_id_1271":"Vehicle Ram Kill - Construction - Large HIVE XP (Target)",
  "GainExperienc_experience_id_1272":"Kill/Destroy - Construction - Large HIVE XP (Target)",
  "GainExperienc_experience_id_1273":"Repair - Construction - Large HIVE XP (Source)",
  "GainExperienc_experience_id_1274":"KillAssist - Construction - Large HIVE XP (Source)",
  "GainExperienc_experience_id_1276":"Spot Kill - Construction - Large  HIVE XP (Source)",
  "GainExperienc_experience_id_1277":"Gunner Kill Share - Construction - Large HIVE XP (Source)",
  "GainExperienc_experience_id_1278":"Gunner Kill Assist Share - Construction - Large HIVE XP (Source)",
  "GainExperienc_experience_id_1279":"Vehicle Passenger Kill Share - Construction - Large HIVE XP (Source)",
  "GainExperienc_experience_id_1280":"Driver Kill Aassist Share - Construction - Large HIVE XP (Source)",
  "GainExperienc_experience_id_1281":"Vehicle Ram Kill - Construction - Core HIVE XP (Source)",
  "GainExperienc_experience_id_1282":"Kill/Destroy - Construction - Core HIVE XP (Source)",
  "GainExperienc_experience_id_1283":"Repair - Construction - Core HIVE XP (Source)",
  "GainExperienc_experience_id_1284":"KillAssist - Construction - Core HIVE XP (Source)",
  "GainExperienc_experience_id_1286":"Spot Kill - Construction - Core  HIVE XP (Source)",
  "GainExperienc_experience_id_1287":"Gunner Kill Share - Construction - Core HIVE XP (Source)",
  "GainExperienc_experience_id_1288":"Gunner Kill Assist Share - Construction - Core HIVE XP (Source)",
  "GainExperienc_experience_id_1289":"Repair - Construction - Large HIVE XP (Target)",
  "GainExperienc_experience_id_1290":"KillAssist - Construction - Large HIVE XP (Target)",
  "GainExperienc_experience_id_1292":"Spot Kill - Construction - Large  HIVE XP (Target)"
}